import { createWorkerViewlet } from '../CreateWorkerViewlet/CreateWorkerViewlet.js'

export const {
  Commands,
  Css,
  Events,
  Variables,
  create,
  dispose,
  focus,
  getCommands,
  getComponentDom,
  getComponentState,
  getKeyBindings,
  getMenus,
  getQuickPickMenuEntries,
  getStorageKey,
  getTitle,
  hasDirectRender,
  hasFunctionalEvents,
  hasFunctionalRender,
  hasFunctionalResize,
  hasFunctionalRootRender,
  hotReload,
  loadContent,
  menus,
  name,
  openEditorWithType,
  openKeyBindings,
  render,
  renderActions,
  renderEventListeners,
  renderTitle,
  resize,
  saveState,
  setComponentState,
  saveWithoutFormatting,
} = createWorkerViewlet({ workerId: 'mainArea' })
