export const editorCreate = (
  id: any,
  uri: string,
  x: number,
  y: number,
  width: number,
  height: number,
  rowHeight: number,
  fontSize: number,
  hoverEnabled: boolean,
  fontFamily: string,
  letterSpacing: number,
  tabSize: number,
  links: boolean,
  lineNumbers: boolean,
  formatOnSave: boolean,
  autoClosingBracketsEnabled: boolean,
  autoClosingTagsEnabled: boolean,
  autoClosingQuotesEnabled: boolean,
  quickSuggestionsEnabled: boolean,
  completionTriggerCharacters: boolean,
  content: string,
  languageId: string,
  tokenizerId: any,
) => {}
