export const WindowWidth = 'windowWidth'
export const WindowHeight = 'windowHeight'

export const MainVisible = 'mainVisible'
export const MainTop = 'mainTop'
export const MainLeft = 'mainLeft'
export const MainWidth = 'mainWidth'
export const MainHeight = 'mainHeight'

export const ActivityBarVisible = 'activityBarVisible'
export const ActivityBarTop = 'activityBarTop'
export const ActivityBarLeft = 'activityBarLeft'
export const ActivityBarWidth = 'activityBarWidth'
export const ActivityBarHeight = 'activityBarHeight'

export const SideBarVisible = 'sideBarVisible'
export const SideBarTop = 'sideBarTop'
export const SideBarLeft = 'sideBarLeft'
export const SideBarWidth = 'sideBarWidth'
export const SideBarHeight = 'sideBarHeight'
export const SideBarMinWidth = 'sideBarMinWidth'
export const SideBarMaxWidth = 'sideBarMaxWidth'

export const PanelVisible = 'panelVisible'
export const panelTop = 'panelTop'
export const PanelLeft = 'panelLeft'
export const PanelWidth = 'panelWidth'
export const PanelHeight = 'panelHeight'
export const PanelMinHeight = 'panelMinHeight'
export const PanelMaxHeight = 'panelMaxHeight'

export const StatusBarVisible = 'statusBarVisible'
export const StatusBarTop = 'statusBarTop'
export const StatusBarLeft = 'statusBarLeft'
export const StatusBarWidth = 'statusBarWidth'
export const StatusBarHeight = 'statusBarHeight'

export const TitleBarVisible = 'titleBarVisible'
export const TitleBarTop = 'titleBarTop'
export const TitleBarLeft = 'titleBarLeft'
export const TitleBarWidth = 'titleBarWidth'
export const TitleBarHeight = 'titleBarHeight'

export const PreviewVisible = 'previewVisible'
export const PreviewTop = 'previewTop'
export const PreviewLeft = 'previewLeft'
export const PreviewWidth = 'previewWidth'
export const PreviewHeight = 'previewHeight'
export const PreviewMinHeight = 'previewMinHeight'
export const PreviewMaxHeight = 'previewMaxHeight'
export const PreviewMinWidth = 'previewMinWidth'
export const PreviewMaxWidth = 'previewMaxWidth'

export const TitleBarNative = 'titleBarNative'

export const Total = 'total'

export const SashId = 'sashId'
