export const Close = '/icons/icon-close.svg'
export const PreviousMatch = '/icons/arrow-up.svg'
export const NextMatch = '/icons/arrow-down.svg'
export const ExtensionDefaultIcon = '/icons/extensionDefaultIcon.png'
export const EXtensionLanguageBasics = '/icons/language-icon.svg'
export const ExtensionTheme = '/icons/theme-icon.png'
