import * as ElementTag from '../ElementTags/ElementTags.ts'
import * as VirtualDomElements from '../VirtualDomElements/VirtualDomElements.ts'

export const getElementTag = (type) => {
  switch (type) {
    case VirtualDomElements.Audio:
      return ElementTag.Audio
    case VirtualDomElements.H1:
      return ElementTag.H1
    case VirtualDomElements.H2:
      return ElementTag.H2
    case VirtualDomElements.H3:
      return ElementTag.H3
    case VirtualDomElements.H4:
      return ElementTag.H4
    case VirtualDomElements.H5:
      return ElementTag.H5
    case VirtualDomElements.H6:
      return ElementTag.H6
    case VirtualDomElements.Div:
      return ElementTag.Div
    case VirtualDomElements.Kbd:
      return ElementTag.Kbd
    case VirtualDomElements.Table:
      return ElementTag.Table
    case VirtualDomElements.TBody:
      return ElementTag.TBody
    case VirtualDomElements.Th:
      return ElementTag.Th
    case VirtualDomElements.Td:
      return ElementTag.Td
    case VirtualDomElements.THead:
      return ElementTag.THead
    case VirtualDomElements.Tr:
      return ElementTag.Tr
    case VirtualDomElements.Input:
      return ElementTag.Input
    case VirtualDomElements.ColGroup:
      return ElementTag.ColGroup
    case VirtualDomElements.Col:
      return ElementTag.Col
    case VirtualDomElements.Button:
      return ElementTag.Button
    case VirtualDomElements.Span:
      return ElementTag.Span
    case VirtualDomElements.I:
      return ElementTag.I
    case VirtualDomElements.Img:
      return ElementTag.Img
    case VirtualDomElements.Ins:
      return ElementTag.Ins
    case VirtualDomElements.Del:
      return ElementTag.Del
    case VirtualDomElements.Article:
      return ElementTag.Article
    case VirtualDomElements.Aside:
      return ElementTag.Aside
    case VirtualDomElements.Footer:
      return ElementTag.Footer
    case VirtualDomElements.Header:
      return ElementTag.Header
    case VirtualDomElements.Nav:
      return ElementTag.Nav
    case VirtualDomElements.Section:
      return ElementTag.Section
    case VirtualDomElements.Search:
      return ElementTag.Search
    case VirtualDomElements.Dd:
      return ElementTag.Dd
    case VirtualDomElements.Dl:
      return ElementTag.Dl
    case VirtualDomElements.Figcaption:
      return ElementTag.Figcaption
    case VirtualDomElements.Figure:
      return ElementTag.Figure
    case VirtualDomElements.Hr:
      return ElementTag.Hr
    case VirtualDomElements.Li:
      return ElementTag.Li
    case VirtualDomElements.Ol:
      return ElementTag.Ol
    case VirtualDomElements.P:
      return ElementTag.P
    case VirtualDomElements.Pre:
      return ElementTag.Pre
    case VirtualDomElements.A:
      return ElementTag.A
    case VirtualDomElements.Br:
      return ElementTag.Br
    case VirtualDomElements.Cite:
      return ElementTag.Cite
    case VirtualDomElements.Data:
      return ElementTag.Data
    case VirtualDomElements.Time:
      return ElementTag.Time
    case VirtualDomElements.Tfoot:
      return ElementTag.Tfoot
    case VirtualDomElements.Ul:
      return ElementTag.Ul
    case VirtualDomElements.Video:
      return ElementTag.Video
    case VirtualDomElements.TextArea:
      return ElementTag.TextArea
    case VirtualDomElements.Select:
      return ElementTag.Select
    case VirtualDomElements.Option:
      return ElementTag.Option
    default:
      throw new Error(`element tag not found ${type}`)
  }
}
