export const ContextMenu = 'context-menu'
export const WillNavigate = 'will-navigate'
export const DidNavigate = 'did-navigate'
export const PageTitleUpdated = 'page-title-updated'
export const Destroyed = 'destroyed'
export const BeforeInputEvent = 'before-input-event'
export const DidFinishLoad = 'did-finish-load'
