image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm ci && cd packages/e2e && npx playwright install chromium && cd ../../ && && cd packages/extension-host-worker-tests && npx playwright install chromium && cd ../../
    command: npm run dev

ports:
  - port: 3000
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
