import * as SendMessagePortToExtensionHostWorker from './SendMessagePortToExtensionHostWorker.js'

export const name = 'SendMessagePortToExtensionHostWorker'

export const Commands = {
  sendMessagePortToChatCoordinatorWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToChatCoordinatorWorker,
  sendMessagePortToChatMathWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToChatMathWorker,
  sendMessagePortToChatNetworkWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToChatNetworkWorker,
  sendMessagePortToChatToolWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToChatToolWorker,
  sendMessagePortToClipBoardWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToClipBoardWorker,
  sendMessagePortToEditorWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToEditorWorker,
  sendMessagePortToErrorWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToErrorWorker,
  sendMessagePortToExtensionHostWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToExtensionHostWorker,
  sendMessagePortToExtensionManagementWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToExtensionManagementWorker,
  sendMessagePortToFileSearchWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToFileSearchWorker,
  sendMessagePortToFileSystemWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToFileSystemWorker,
  sendMessagePortToIconThemeWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToIconThemeWorker,
  sendMessagePortToIframeWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToIframeWorker,
  sendMessagePortToMainAreaWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToMainAreaWorker,
  sendMessagePortToMarkdownWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToMarkdownWorker,
  sendMessagePortToOpenerWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToOpenerWorker,
  sendMessagePortToPreviewSandBoxWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToPreviewSandBoxWorker,
  sendMessagePortToRendererProcess: SendMessagePortToExtensionHostWorker.sendMessagePortToRendererProcess,
  sendMessagePortToSharedProcess: SendMessagePortToExtensionHostWorker.sendMessagePortToSharedProcess,
  sendMessagePortToSourceControlWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToSourceControlWorker,
  sendMessagePortToTextMeasurementWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToTextMeasurementWorker,
}
