import * as SendMessagePortToExtensionHostWorker from './SendMessagePortToExtensionHostWorker.js'

export const name = 'SendMessagePortToExtensionHostWorker'

export const Commands = {
  sendMessagePortToEditorWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToEditorWorker,
  sendMessagePortToErrorWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToErrorWorker,
  sendMessagePortToExtensionHostWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToExtensionHostWorker,
  sendMessagePortToExtensionManagementWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToExtensionManagementWorker,
  sendMessagePortToFileSearchWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToFileSearchWorker,
  sendMessagePortToFileSystemWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToFileSystemWorker,
  sendMessagePortToIconThemeWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToIconThemeWorker,
  sendMessagePortToIframeWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToIframeWorker,
  sendMessagePortToMarkdownWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToMarkdownWorker,
  sendMessagePortToRendererProcess: SendMessagePortToExtensionHostWorker.sendMessagePortToRendererProcess,
  sendMessagePortToSharedProcess: SendMessagePortToExtensionHostWorker.sendMessagePortToSharedProcess,
  sendMessagePortToSourceControlWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToSourceControlWorker,
  sendMessagePortToTextMeasurementWorker: SendMessagePortToExtensionHostWorker.sendMessagePortToTextMeasurementWorker,
}
