export const SymbolProperty = 'SymbolProperty'
export const SymbolValue = 'SymbolValue'
export const SymbolFunction = 'SymbolFunction'
export const SymbolVariable = 'SymbolVariable'
export const SymbolKeyword = 'SymbolKeyword'
export const SymbolDefault = 'SymbolDefault'
export const SymbolField = 'SymbolField'
export const SymbolNone = ''
