/**
 * @param {string} id
 */
export const getCommandInfo = (id) => {
  switch (id) {
    case 'file.openFolder':
      return 1492
    case 'file.openRecent':
      return 18926
    case 'help.about':
      return 1493
    case 'main.openEditor':
      return 88
    case 'main.save':
      return 89
    case 'main.closeActiveEditor':
      return 93
    case 'main.closeEditor':
      return 99
    case 'main.closeAllEditors':
      return 94
    case 'main.focusFirst':
      return 101
    case 'main.focusLast':
      return 102
    case 'main.focusPrevious':
      return 103
    case 'main.focusNext':
      return 104
    case 'viewletExplorer.focusNext':
      return 142
    case 'viewletExplorer.focusPrevious':
      return 143
    case 'viewletExplorer.scrollUp':
      return 144
    case 'viewletExplorer.scrollDown':
      return 145
    case 'viewletExplorer.handleClickCurrent':
      return 146
    case 'viewletExplorer.newFile':
      return 147
    case 'viewletExplorer.openContainingFolder':
      return 148
    case 'viewletExplorer.copyPath':
      return 149
    case 'viewletExplorer.copyRelativePath':
      return 150
    case 'viewletExplorer.removeDirent':
      return 151
    case 'viewletExplorer.newFolder':
      return 152
    case 'viewletExplorer.handleArrowRight':
      return 154
    case 'viewletExplorer.handleArrowLeft':
      return 155
    case 'viewletExplorer.focusFirst':
      return 156
    case 'viewletExplorer.focusLast':
      return 157
    case 'viewletExplorer.rename':
      return 158
    case 'viewletExplorer.handlePaste':
      return 165
    case 'viewletExplorer.handleCopy':
      return 166
    case 'viewletExplorer.cancelRename':
      return 167
    case 'viewletExplorer.acceptRename':
      return 168
    case 'viewletExplorer.cancelNewFile':
      return 169
    case 'viewletExplorer.acceptNewFile':
      return 170
    case 'viewletExplorer.expandAll':
      return 171
    case 'viewletExplorer.collapseAll':
      return 172
    case 'editor.handleContextMenu':
      return 87
    case 'editor.cursorDown':
      return 341
    case 'editor.cursorLeft':
      return 342
    case 'editor.cursorRight':
      return 343
    case 'editor.cursorUp':
      return 344
    case 'editor.type':
      return 345
    case 'editor.deleteLeft':
      return 346
    case 'editor.deleteRight':
      return 347
    case 'editor.insertLineBreak':
      return 348
    case 'editor.copyLineUp':
      return 349
    case 'editor.copyLineDown':
      return 350
    case 'editor.moveLineDown':
      return 351
    case 'editor.cursorWordLeft':
      return 352
    case 'editor.cursorWordRight':
      return 353
    case 'editor.deleteWordLeft':
      return 354
    case 'editor.deleteWordRight':
      return 355
    case 'editor.moveLineUp':
      return 356
    case 'editor.tabCompletion':
      return 357
    case 'editor.cursorHome':
      return 358
    case 'editor.cursorEnd':
      return 359
    case 'editor.handleClick':
      return 360
    case 'editor.handleDoubleClick':
      return 361
    case 'editor.toggleBlockComment':
      return 362
    case 'editor.moveSelection':
      return 363
    case 'editor.cut':
      return 364
    case 'editor.copy':
      return 365
    case 'editor.selectAll':
      return 366
    case 'editor.moveRectangleSelection':
      return 367
    case 'editor.cursorWordPartRight':
      return 368
    case 'editor.cursorWordPartLeft':
      return 369
    case 'editor.blur':
      return 370
    case 'editor.scheduleDocument':
      return 372
    case 'editor.toggleComment':
      return 373
    case 'editor.deleteAllLeft':
      return 374
    case 'editor.deleteAllRight':
      return 375
    case 'editor.handleTripleClick':
      return 376
    case 'editor.selectLine':
      return 377
    case 'editor.selectCharacterLeft':
      return 380
    case 'editor.selectCharacterRight':
      return 381
    case 'editor.selectWordLeft':
      return 402
    case 'editor.selectWordRight':
      return 401
    case 'editor.format':
      return 388
    case 'editor.selectNextOccurrence':
      return 390
    case 'editor.selectAllOccurrences':
      return 391
    case 'editor.handleTab':
      return 392
    case 'editor.cancelSelection':
      return 393
    case 'editor.unindent':
      return 394
    case 'editor.undo':
      return 395
    case 'editor.formatForced':
      return -1
    case 'editor.deleteWordPartLeft':
      return 397
    case 'editor.deleteWordPartRight':
      return 398
    case 'editor.indentMore':
      return 409
    case 'editor.indentLess':
      return 410
    case 'viewService.toggleView':
      return 1105
    case 'viewletExtensions.openSuggest':
      return 860
    case 'viewletExtensions.closeSuggest':
      return 861
    case 'viewletExtensions.toggleSuggest':
      return 862
    case 'contextMenu.select':
      return 950
    case 'contextMenu.show':
      return 951
    // TODO decide on one name
    case 'contextMenu.hide':
    case 'contextMenu.close':
      return 952
    case 'menu.focusFirst':
      return 7406
    case 'menu.focusLast':
      return 7407
    case 'menu.focusNext':
      return 7404
    case 'menu.focusPrevious':
      return 7405
    case 'contextMenu.selectCurrent':
      return 957
    case 'editorCompletion.open':
      return 980
    case 'editorCompletion.close':
      return 981
    case 'editorCompletion.selectIndex':
      return 982
    case 'editorCompletion.focusFirst':
      return 983
    case 'editorCompletion.focusLast':
      return 984
    case 'editorCompletion.focusNext':
      return 985
    case 'editorCompletion.focusPrevious':
      return 986
    case 'editorCompletion.selectCurrent':
      return 987
    case 'editorCompletion.openFromType':
      return 988
    case 'quickPickHide':
      return 71178
    case 'layout.showSideBar':
      return 1100
    case 'layout.hideSideBar':
      return 1101
    case 'layout.toggleSideBar':
      return 1102
    case 'layout.showPanel':
      return 1103
    case 'layout.hidePanel':
      return 1104
    case 'layout.togglePanel':
      return 1105
    case 'layout.showActivityBar':
      return 1106
    case 'layout.hideActivityBar':
      return 1107
    case 'layout.toggleActivityBar':
      return 1108
    case 'focus.set':
      return 1103
    case 'focus.output':
      // TODO arg
      return 1103
    case 'focus.search':
      // TODO arg
      return 1103
    case 'focus.sourceControl':
      // TODO arg
      return 1103
    case 'focus.debugAndRun':
      // TODO arg
      return 1103
    case 'focus.extensions':
      // TODO arg
      return 1103
    case 'focus.nextPart':
      return 5741
    case 'focus.previousPart':
      return 5740
    case 'focus.statusBar':
      return 5743
    case 'window.close':
      return 8084
    case 'window.reload':
      return 8080
    case 'window.makeScreenshot':
      return 8085
    case 'window.minimize':
      return 8081
    case 'window.maximize':
      return 8082
    case 'window.unmaximize':
      return 8083
    case 'developer.measureLatencyBetweenExtensionHostAndSharedProcess':
      return 281
    case 'developer.measureLatencyBetweenSharedProcessAndRendererProcess':
      return 282
    case 'developer.showState':
      return 283
    case 'developer.startupPerformance':
      return 833
    case 'developer.showMemoryUsage':
      return 834
    case 'developer.allocateMemoryInSharedProcess':
      return 822
    case 'developer.crashSharedProcess':
      return 823
    case 'developer.createSharedProcessHeapSnapshot':
      return 824
    case 'developer.createSharedProcessProfile':
      return 825
    case 'developer.showIconThemeCss':
      return 826
    case 'developer.reloadIconTheme':
      return 827
    case 'developer.clearCache':
      return 828
    case 'developer.toggleDeveloperTools':
      return 831
    case 'developer.crashMainProcess':
      return 832
    case 'developer.openConfigFolder':
      return 835
    case 'developer.openDataFolder':
      return 836
    case 'developer.openCacheFolder':
      return 838
    case 'developer.openProcessExplorer':
      return 839
    case 'preferences.openSettingsJson':
      return 1200
    case 'preferences.openUserKeyBindings':
      return 1201
    case 'preferences.openDefaultKeyBindings':
      return 1202
    case 'preferences.selectColorTheme':
      return 18925
    case 'extensions.openExtensionsFolder':
      return 7650
    case 'extensions.openCachedExtensionsFolder':
      return 7651
    case 'viewletExtensions.focusFirst':
      return 869
    case 'viewletExtensions.focusLast':
      return 870
    case 'viewletExtensions.focusPrevious':
      return 871
    case 'viewletExtensions.focusNext':
      return 872
    case 'viewletExtensions.focusNextPage':
      return 874
    case 'viewletExtensions.focusPreviousPage':
      return 875
    case 'focus.activityBar':
      return 8003
    case 'focus.titleBar':
      return 4512
    case 'developer.reloadColorTheme':
      return 829
    case 'developer.showColorThemeCss':
      return 830
    case 'activityBar.focusNext':
      return 8004
    case 'activityBar.focusFirst':
      return 8006
    case 'activityBar.focusLast':
      return 8007
    case 'activityBar.focusPrevious':
      return 8005
    case 'activityBar.selectCurrent':
      return 8008
    case 'terminal.clear':
      return 4871
    case 'editor.openColorPicker':
      return 1400
    case 'editor.closeColorPicker':
      return 1401
    case 'quickPick.show':
      return 71179
    case 'quickPick.hide':
      return 71178
    case 'quickPick.selectCurrentIndex':
      return 71180
    case 'quickPick.handleInput':
      return 71181
    case 'quickPick.selectIndex':
      return 71182
    // TODO maybe rename to showCommands
    case 'menu.show':
      return 7400
    case 'menu.hide':
      return 7401
    case 'quickPick.openCommandPalette':
      return 7611
    case 'quickPick.openView':
      return 7612
    case 'quickPick.focusFirst':
      return 18920
    case 'quickPick.focusLast':
      return 18921
    case 'quickPick.focusPrevious':
      return 18922
    case 'quickPick.focusNext':
      return 18923
    case 'quickPick.openGoToLine':
      return 18924
    case 'titleBarMenuBar.handleClick':
      return 4610
    case 'titleBarMenuBar.focus':
      return 4612
    case 'titleBarMenuBar.focusIndex':
      return 4613
    case 'titleBarMenuBar.focusPrevious':
      return 4614
    case 'titleBarMenuBar.focusNext':
      return 4615
    case 'titleBarMenuBar.closeMenu':
      return 4616
    case 'titleBarMenuBar.openMenu':
      return 4617
    case 'navigation.focusPreviousPart':
      return 5740
    case 'navigation.focusNextPart':
      return 5741
    case 'editorRename.open':
      return 3300
    case 'editorRename.finish':
      return 3301
    case 'editorRename.abort':
      return 3302
    case 'editor.goToDefinition':
      return 414
    case 'editor.selectInsideString':
      return 403
    case 'notification.create':
      return 900
    case 'notification.dispose':
      return 901
    case 'viewletSourceControl.acceptInput':
      return 6532
    case 'dialog.close':
      return 1495
    case 'audio.playBell':
      return 4444
    case 'serviceWorker.uninstall':
      return 5784
    case 'developer.openLogsFolder':
      return 837
    case 'workbench.newWindow':
      return 8086
    case 'contextMenu.noop':
      return 958
    case 'viewletLocations.focusFirst':
      return 7101
    case 'viewletLocations.focusLast':
      return 7102
    case 'viewletLocations.focusNext':
      return 7103
    case 'viewletLocations.focusPrevious':
      return 7104
    case 'viewletLocations.selectCurrent':
      return 7105
    default:
      console.warn(`[CommandInfo] unknown command "${id}"`)
      return -1
  }
}
