export const ExtensionHost = 'extension-host'
export const ExtensionHostHelperProcess = 'extension-host-helper-process'
export const SearchProcess = 'search-process'
export const SharedProcess = 'shared-process'
export const TerminalProcess = 'terminal-process'
