export const HandleElectronMessagePort = 'HandleElectronMessagePort.handleElectronMessagePort'
export const HandleNodeMessagePort = 'HandleNodeMessagePort.handleNodeMessagePort'
export const HandleWebSocket = 'HandleWebSocket.handleWebSocket'
export const TerminalCreate = 'Terminal.create'
export const TerminalResize = 'Terminal.resize'
export const TerminalWrite = 'Terminal.write'
export const TerminalDispose = 'Terminal.dispose'
