export const HandleEditorDeleteLeft = 'handleEditorDeleteLeft'
export const HandleEditorType = 'handleEditorType'
export const HandleEditorBlur = 'handleEditorBlur'
export const HandleEditorClick = 'handleEditorClick'
export const HandleCursorMove = 'handleCursorMove'
