export const Css = [
  '/css/parts/Alignment.css',
  '/css/parts/Badge.css',
  '/css/parts/Chevron.css',
  '/css/parts/FileIcon.css',
  '/css/parts/Highlight.css',
  '/css/parts/InputBox.css',
  '/css/parts/Label.css',
  '/css/parts/MaskIcon.css',
  '/css/parts/ScrollBar.css',
  '/css/parts/SearchField.css',
  '/css/parts/SearchHeader.css',
  '/css/parts/SearchToggleButton.css',
  '/css/parts/TreeItem.css',
  '/css/parts/ViewletList.css',
  '/css/parts/ViewletSearch.css',
  '/css/parts/SearchMessage.css',
]
