import * as ViewletLayout from './ViewletLayout.ts'

// prettier-ignore
export const Commands = {
}

export const CommandsWithSideEffects = {
  handleSashPointerDown: ViewletLayout.handleSashPointerDown,
  handleSashPointerUp: ViewletLayout.handleSashPointerUp,
  handleResize: ViewletLayout.handleResize,
  handleSashDoubleClick: ViewletLayout.handleSashDoubleClick,
  handleSashPointerMove: ViewletLayout.handleSashPointerMove,
  hideActivityBar: ViewletLayout.hideActivityBar,
  hideMain: ViewletLayout.hideMain,
  hidePanel: ViewletLayout.hidePanel,
  hideSideBar: ViewletLayout.hideSideBar,
  hideStatusBar: ViewletLayout.hideStatusBar,
  hideTitleBar: ViewletLayout.hideTitleBar,
  loadActivityBarIfVisible: ViewletLayout.loadActivityBarIfVisible,
  loadMainIfVisible: ViewletLayout.loadMainIfVisible,
  loadPreviewIfVisible: ViewletLayout.loadPreviewIfVisible,
  loadPanelIfVisible: ViewletLayout.loadPanelIfVisible,
  loadSideBarIfVisible: ViewletLayout.loadSideBarIfVisible,
  loadStatusBarIfVisible: ViewletLayout.loadStatusBarIfVisible,
  loadTitleBarIfVisible: ViewletLayout.loadTitleBarIfVisible,
  showActivityBar: ViewletLayout.showActivityBar,
  showMain: ViewletLayout.showMain,
  showPanel: ViewletLayout.showPanel,
  showSideBar: ViewletLayout.showSideBar,
  showStatusBar: ViewletLayout.showStatusBar,
  showTitleBar: ViewletLayout.showTitleBar,
  showPreview: ViewletLayout.showPreview,
  togglePreview: ViewletLayout.togglePreview,
  hidePreview: ViewletLayout.hidePreview,
  toggleActivityBar: ViewletLayout.toggleActivityBar,
  toggleMain: ViewletLayout.toggleMain,
  togglePanel: ViewletLayout.togglePanel,
  toggleSideBar: ViewletLayout.toggleSideBar,
  toggleStatusBar: ViewletLayout.toggleStatusBar,
  toggleTitleBar: ViewletLayout.toggleTitleBar,
  moveSideBarLeft: ViewletLayout.moveSideBarLeft,
  moveSideBarRight: ViewletLayout.moveSideBarRight,
  toggleSideBarPosition: ViewletLayout.toggleSideBarPosition,
  handleBlur: ViewletLayout.handleBlur,
  handleFocus: ViewletLayout.handleFocus,
  showE2eTests: ViewletLayout.showE2eTests,
  setUpdateState: ViewletLayout.setUpdateState,
}
