import * as ModuleId from '../ModuleId/ModuleId.ts'

export const load = (moduleId: any): any => {
  switch (moduleId) {
    case ModuleId.AttachDebugger:
      return import('../AttachDebugger/AttachDebugger.ipc.ts')
    case ModuleId.AutoUpdater:
      return import('../AutoUpdater/AutoUpdater.ipc.ts')
    case ModuleId.AutoUpdaterAppImage:
      return import('../AutoUpdaterAppImage/AutoUpdaterAppImage.ipc.ts')
    case ModuleId.GetWindowId:
      return import('../GetWindowId/GetWindowId.ipc.ts')
    case ModuleId.AutoUpdaterWindowsNsis:
      return import('../AutoUpdaterWindowsNsis/AutoUpdaterWindowsNsis.ipc.ts')
    case ModuleId.BulkReplacement:
      return import('../BulkReplacement/BulkReplacement.ipc.ts')
    case ModuleId.Exec:
      return import('../Exec/Exec.ipc.ts')
    case ModuleId.ClipBoard:
      return import('../ClipBoard/ClipBoard.ipc.ts')
    case ModuleId.Crash:
      return import('../Crash/Crash.ipc.ts')
    case ModuleId.DesktopCapturer:
      return import('../DesktopCapturer/DesktopCapturer.ipc.ts')
    case ModuleId.Developer:
      return import('../Developer/Developer.ipc.ts')
    case ModuleId.Download:
      return import('../Download/Download.ipc.ts')
    case ModuleId.ElectronApplicationMenu:
      return import('../ElectronApplicationMenu/ElectronApplicationMenu.ipc.ts')
    case ModuleId.ElectronContentTracing:
      return import('../ElectronContentTracing/ElectronContentTracing.ipc.ts')
    case ModuleId.ElectronDeveloper:
      return import('../ElectronDeveloper/ElectronDeveloper.ipc.ts')
    case ModuleId.ElectronContextMenu:
      return import('../ElectronContextMenu/ElectronContextMenu.ipc.ts')
    case ModuleId.ElectronDialog:
      return import('../ElectronDialog/ElectronDialog.ipc.ts')
    case ModuleId.ElectronInitialize:
      return import('../ElectronInitialize/ElectronInitialize.ipc.ts')
    case ModuleId.ElectronNetLog:
      return import('../ElectronNetLog/ElectronNetLog.ipc.ts')
    case ModuleId.ElectronProcess:
      return import('../ElectronProcess/ElectronProcess.ipc.ts')
    case ModuleId.ElectronSafeStorage:
      return import('../ElectronSafeStorage/ElectronSafeStorage.ipc.ts')
    case ModuleId.Window:
      return import('../ElectronWindow/ElectronWindow.ipc.ts')
    case ModuleId.ElectronWindowAbout:
      return import('../ElectronWindowAbout/ElectronWindowAbout.ipc.ts')
    case ModuleId.ElectronWindowProcessExplorer:
      return import('../ElectronWindowProcessExplorer/ElectronWindowProcessExplorer.ipc.ts')
    case ModuleId.Exit:
      return import('../Exit/Exit.ipc.ts')
    case ModuleId.HandleRequestTest:
      return import('../HandleRequestTest/HandleRequestTest.ipc.ts')
    case ModuleId.ExtensionManagement:
      return import('../ExtensionManagement/ExtensionManagement.ipc.ts')
    case ModuleId.FileSystem:
      return import('../FileSystem/FileSystem.ipc.ts')
    case ModuleId.GetTerminalSpawnOptions:
      return import('../GetTerminalSpawnOptions/GetTerminalSpawnOptions.ipc.ts')
    case ModuleId.GitLsFiles:
      return import('../GitLsFiles/GitLsFiles.ipc.ts')
    case ModuleId.HandleCliArgs:
      return import('../HandleCliArgs/HandleCliArgs.ipc.ts')
    case ModuleId.HandleElectronMessagePort:
      return import('../HandleElectronMessagePort/HandleElectronMessagePort.ipc.ts')
    case ModuleId.HandleNodeMessagePort:
      return import('../HandleNodeMessagePort/HandleNodeMessagePort.ipc.ts')
    case ModuleId.HandleWebSocket:
      return import('../HandleWebSocket/HandleWebSocket.ipc.ts')
    case ModuleId.InstallExtension:
      return import('../InstallExtension/InstallExtension.ipc.ts')
    case ModuleId.IsAutoUpdateSupported:
      return import('../IsAutoUpdateSupported/IsAutoUpdateSupported.ipc.ts')
    case ModuleId.OpenExternal:
      return import('../OpenExternal/OpenExternal.ipc.ts')
    case ModuleId.OpenNativeFolder:
      return import('../OpenNativeFolder/OpenNativeFolder.ipc.ts')
    case ModuleId.ElectronPowerSaveBlocker:
      return import('../ElectronPowerSaveBlocker/ElectronPowerSaveBlocker.ipc.ts')
    case ModuleId.Os:
      return import('../Os/Os.ipc.ts')
    case ModuleId.PlatformPaths:
      return import('../PlatformPaths/PlatformPaths.ipc.ts')
    case ModuleId.HandleMessagePortForAuthProcess:
      return import('../HandleMessagePortForAuthProcess/HandleMessagePortForAuthProcess.ipc.ts')
    case ModuleId.OutputChannel:
      return import('../OutputChannel/OutputChannel.ipc.ts')
    case ModuleId.Performance:
      return import('../Performance/Performance.ipc.ts')
    case ModuleId.Platform:
      return import('../Platform/Platform.ipc.ts')
    case ModuleId.Preferences:
      return import('../Preferences/Preferences.ipc.ts')
    case ModuleId.Process:
      return import('../Process/Process.ipc.ts')
    case ModuleId.ProcessExplorer:
      return import('../ProcessExplorer/ProcessExplorer.ipc.ts')
    case ModuleId.ProcessId:
      return import('../ProcessId/ProcessId.ipc.ts')
    case ModuleId.RebuildNodePty:
      return import('../RebuildNodePty/RebuildNodePty.ipc.ts')
    case ModuleId.RecentlyOpened:
      return import('../RecentlyOpened/RecentlyOpened.ipc.ts')
    case ModuleId.Terminal:
      return import('../Terminal/Terminal.ipc.ts')
    case ModuleId.TextDocument:
      return import('../TextDocument/TextDocument.ipc.ts')
    case ModuleId.Workspace:
      return import('../Workspace/Workspace.ipc.ts')
    case ModuleId.ElectronNet:
      return import('../ElectronNet/ElectronNet.ipc.ts')
    case ModuleId.Screen:
      return import('../Screen/Screen.ipc.ts')
    case ModuleId.HandleElectronReady:
      return import('../HandleElectronReady/HandleElectronReady.ipc.ts')
    case ModuleId.HandleWindowAllClosed:
      return import('../HandleWindowAllClosed/HandleWindowAllClosed.ipc.ts')
    case ModuleId.HandleMessagePortForTerminalProcess:
      return import('../HandleMessagePortForTerminalProcess/HandleMessagePortForTerminalProcess.ipc.ts')
    case ModuleId.HandleMessagePortForEmbedsProcess:
      return import('../HandleMessagePortForEmbedsProcess/HandleMessagePortForEmbedsProcess.ipc.ts')
    case ModuleId.HandleMessagePortForFileSystemProcess:
      return import('../HandleMessagePortForFileSystemProcess/HandleMessagePortForFileSystemProcess.ipc.ts')
    case ModuleId.TemporaryMessagePort:
      return import('../TemporaryMessagePort/TemporaryMessagePort.ipc.ts')
    case ModuleId.GetElectronFileResponse:
      return import('../GetElectronFileResponse/GetElectronFileResponse.ipc.ts')
    case ModuleId.HandleRemoteRequest:
      return import('../HandleRemoteRequest/HandleRemoteRequest.ipc.ts')
    case ModuleId.HandleMessagePortForExtensionHostHelperProcess:
      return import('../HandleMessagePortForExtensionHostHelperProcess/HandleMessagePortForExtensionHostHelperProcess.ipc.ts')
    case ModuleId.ContentSecurityPolicy:
      return import('../ContentSecurityPolicy/ContentSecurityPolicy.ipc.ts')
    case ModuleId.HandleMessagePortForProcessExplorer:
      return import('../HandleMessagePortForProcessExplorer/HandleMessagePortForProcessExplorer.ipc.ts')
    case ModuleId.HandleMessagePortForSearchProcess:
      return import('../HandleMessagePortForSearchProcess/HandleMessagePortForSearchProcess.ipc.ts')
    case ModuleId.FileWatcher:
      return import('../FileWatcher/FileWatcher.ipc.ts')
    case ModuleId.WebViewServer:
      return import('../WebViewServer/WebViewServer.ipc.ts')
    case ModuleId.GetExtensions:
      return import('../GetExtensions/GetExtensions.ipc.ts')
    case ModuleId.FileSystemDisk:
      return import('../FileSystemDisk/FileSystemDisk.ipc.ts')
    case ModuleId.HandleRequest:
      return import('../HandleRequest/HandleRequest.ipc.ts')
    case ModuleId.HandleMessagePortForClipBoardProcess:
      return import('../HandleMessagePortForClipBoardProcess/HandleMessagePortForClipBoardProcess.ipc.ts')
    default:
      throw new Error(`module ${moduleId} not found`)
  }
}
