import * as ModuleId from '../ModuleId/ModuleId.js'

export const load = (moduleId) => {
  switch (moduleId) {
    case ModuleId.About:
      return import('../About/About.ipc.js')
    case ModuleId.Ajax:
      return import('../Ajax/Ajax.ipc.js')
    case ModuleId.Audio:
      return import('../Audio/Audio.ipc.js')
    case ModuleId.AutoUpdater:
      return import('../AutoUpdater/AutoUpdater.ipc.js')
    case ModuleId.GetActiveEditor:
      return import('../GetActiveEditor/GetActiveEditor.ipc.js')
    case ModuleId.Document:
      return import('../Document/Document.ipc.js')
    case ModuleId.Exec:
      return import('../Exec/Exec.ipc.js')
    case ModuleId.GetEditorSourceActions:
      return import('../GetEditorSourceActions/GetEditorSourceActions.ipc.js')
    case ModuleId.PlatformPaths:
      return import('../PlatformPaths/PlatformPaths.ipc.js')
    case ModuleId.FileSystemHandle:
      return import('../FileSystemHandle/FileSystemHandle.ipc.js')
    case ModuleId.Blob:
      return import('../Blob/Blob.ipc.js')
    case ModuleId.BulkReplacement:
      return import('../BulkReplacement/BulkReplacement.ipc.js')
    case ModuleId.CacheStorage:
      return import('../CacheStorage/CacheStorage.ipc.js')
    case ModuleId.Callback:
      return import('../Callback/Callback.ipc.js')
    case ModuleId.Chrome:
      return import('../Chrome/Chrome.ipc.js')
    case ModuleId.ClipBoard:
      return import('../ClipBoard/ClipBoard.ipc.js')
    case ModuleId.ColorTheme:
      return import('../ColorTheme/ColorTheme.ipc.js')
    case ModuleId.ConfirmPrompt:
      return import('../ConfirmPrompt/ConfirmPrompt.ipc.js')
    case ModuleId.ContentTracing:
      return import('../ContentTracing/ContentTracing.ipc.js')
    case ModuleId.ContextMenu:
      return import('../ContextMenu/ContextMenu.ipc.js')
    case ModuleId.Debug:
      return import('../Debug/Debug.ipc.js')
    case ModuleId.DebugSharedProcess:
      return import('../DebugSharedProcess/DebugSharedProcess.ipc.js')
    case ModuleId.Developer:
      return import('../Developer/Developer.ipc.js')
    case ModuleId.Dialog:
      return import('../Dialog/Dialog.ipc.js')
    case ModuleId.Download:
      return import('../Download/Download.ipc.js')
    case ModuleId.EditorDiagnostics:
      return import('../EditorDiagnostics/EditorDiagnostics.ipc.js')
    case ModuleId.EditorError:
      return import('../EditorError/EditorError.ipc.js')
    case ModuleId.ElectronBrowserView:
      return import('../ElectronBrowserView/ElectronBrowserView.ipc.js')
    case ModuleId.ElectronClipBoard:
      return import('../ElectronClipBoard/ElectronClipBoard.ipc.js')
    case ModuleId.ElectronContextMenu:
      return import('../ElectronContextMenu/ElectronContextMenu.ipc.js')
    case ModuleId.ElectronWindow:
      return import('../ElectronWindow/ElectronWindow.ipc.js')
    case ModuleId.ErrorHandling:
      return import('../ErrorHandling/ErrorHandling.ipc.js')
    case ModuleId.Exit:
      return import('../Exit/Exit.ipc.js')
    case ModuleId.ExtensionHostCode:
      return import('../ExtensionHost/ExtensionHostCore.ipc.js')
    case ModuleId.ExtensionMeta:
      return import('../ExtensionMeta/ExtensionMeta.ipc.js')
    case ModuleId.Extensions:
      return import('../Extensions/Extensions.ipc.js')
    case ModuleId.FilePicker:
      return import('../FilePicker/FilePicker.ipc.js')
    case ModuleId.FileSystem:
      return import('../FileSystem/FileSystem.ipc.js')
    case ModuleId.IconTheme:
      return import('../IconTheme/IconTheme.ipc.js')
    case ModuleId.ImagePreview:
      return import('../ImagePreview/ImagePreview.ipc.js')
    case ModuleId.Focus:
      return import('../Focus/Focus.ipc.js')
    case ModuleId.IndexedDb:
      return import('../IndexedDb/IndexedDb.ipc.js')
    case ModuleId.IpcParent:
      return import('../IpcParent/IpcParent.ipc.js')
    case ModuleId.KeyBindings:
      return import('../KeyBindings/KeyBindings.ipc.js')
    case ModuleId.KeyBindingsInitial:
      return import('../KeyBindingsInitial/KeyBindingsInitial.ipc.js')
    case ModuleId.Listener:
      return import('../Listener/Listener.ipc.js')
    case ModuleId.LocalStorage:
      return import('../LocalStorage/LocalStorage.ipc.js')
    case ModuleId.Menu:
      return import('../Menu/Menu.ipc.js')
    case ModuleId.Mime:
      return import('../Mime/Mime.ipc.js')
    case ModuleId.NativeHost:
      return import('../NativeHost/NativeHost.ipc.js')
    case ModuleId.Navigation:
      return import('../Navigation/Navigation.ipc.js')
    case ModuleId.Notification:
      return import('../Notification/Notification.ipc.js')
    case ModuleId.Open:
      return import('../Open/Open.ipc.js')
    case ModuleId.OpenNativeFolder:
      return import('../OpenNativeFolder/OpenNativeFolder.ipc.js')
    case ModuleId.PersistentFileHandle:
      return import('../PersistentFileHandle/PersistentFileHandle.ipc.js')
    case ModuleId.Preferences:
      return import('../Preferences/Preferences.ipc.js')
    case ModuleId.Prompt:
      return import('../Prompt/Prompt.ipc.js')
    case ModuleId.RebuildNodePty:
      return import('../RebuildNodePty/RebuildNodePty.ipc.js')
    case ModuleId.RecentlyOpened:
      return import('../RecentlyOpened/RecentlyOpened.ipc.js')
    case ModuleId.Reload:
      return import('../Reload/Reload.ipc.js')
    case ModuleId.SaveFileAs:
      return import('../SaveFileAs/SaveFileAs.ipc.js')
    case ModuleId.SaveState:
      return import('../SaveState/SaveState.ipc.js')
    case ModuleId.SessionReplay:
      return import('../SessionReplay/SessionReplay.ipc.js')
    case ModuleId.SessionStorage:
      return import('../SessionStorage/SessionStorage.ipc.js')
    case ModuleId.Test:
      return import('../Test/Test.ipc.js')
    case ModuleId.TestFrameWork:
      return import('../TestFrameWork/TestFrameWork.ipc.js')
    case ModuleId.Url:
      return import('../Url/Url.ipc.js')
    case ModuleId.Viewlet:
      return import('../Viewlet/Viewlet.ipc.js')
    case ModuleId.Window:
      return import('../Window/Window.ipc.js')
    case ModuleId.Workspace:
      return import('../Workspace/Workspace.ipc.js')
    case ModuleId.WindowTitle:
      return import('../WindowTitle/WindowTitle.ipc.js')
    case ModuleId.PointerCapture:
      return import('../PointerCapture/PointerCapture.ipc.js')
    case ModuleId.QuickPick:
      return import('../QuickPick/QuickPick.ipc.js')
    case ModuleId.ExtensionHostQuickPick:
      return import('../ExtensionHost/ExtensionHostQuickPick.ipc.js')
    case ModuleId.ExtensionHostDialog:
      return import('../ExtensionHost/ExtensionHostDialog.ipc.js')
    case ModuleId.ExtensionHostWorkerContentSecurityPolicy:
      return import('../ExtensionHost/ExtensionHostWorkerContentSecurityPolicy.ipc.js')
    case ModuleId.SendMessagePortToElectron:
      return import('../SendMessagePortToElectron/SendMessagePortToElectron.ipc.js')
    case ModuleId.OffscreenCanvas:
      return import('../OffscreenCanvas/OffscreenCanvas.ipc.js')
    case ModuleId.Timeout:
      return import('../Timeout/Timeout.ipc.js')
    case ModuleId.MouseActions:
      return import('../MouseActions/MouseActions.ipc.ts')
    case ModuleId.Languages:
      return import('../Languages/Languages.ipc.js')
    case ModuleId.FileWatcher:
      return import('../FileWatcher/FileWatcher.ipc.js')
    case ModuleId.ExtensionHostSelection:
      return import('../ExtensionHost/ExtensionHostSelection.ipc.js')
    case ModuleId.ExtensionHostBraceCompletion:
      return import('../ExtensionHost/ExtensionHostBraceCompletion.ipc.js')
    case ModuleId.ExtensionHostDefinition:
      return import('../ExtensionHost/ExtensionHostDefinition.ipc.js')
    case ModuleId.ExtensionHostTypeDefinition:
      return import('../ExtensionHost/ExtensionHostTypeDefinition.ipc.js')
    case ModuleId.ExtensionHostOrganizeImports:
      return import('../ExtensionHost/ExtensionHostOrganizeImports.ipc.js')
    case ModuleId.ExtensionHostTabCompletion:
      return import('../ExtensionHost/ExtensionHostTabCompletion.ipc.js')
    case ModuleId.ExtensionHostClosingTag:
      return import('../ExtensionHost/ExtensionHostClosingTagCompletion.ipc.js')
    case ModuleId.SendMessagePortToRendererProcess:
      return import('../SendMessagePortToRendererProcess/SendMessagePortToRendererProcess.ipc.js')
    case ModuleId.ExtensionHostHover:
      return import('../ExtensionHost/ExtensionHostHover.ipc.js')
    case ModuleId.SendMessagePortToExtensionHostWorker:
      return import('../SendMessagePortToExtensionHostWorker/SendMessagePortToExtensionHostWorker.ipc.js')
    case ModuleId.ExtensionHostManagement:
      return import('../ExtensionHostManagement/ExtensionHostManagement.ipc.js')
    case ModuleId.SendMessagePortToSyntaxHighlightingWorker:
      // TODO move this to transferrable module instead
      return import('../SendMessagePortToSyntaxHighlightingworker/SendMessagePortToSyntaxHighlightingWorker.ipc.js')
    case ModuleId.Transferrable:
      return import('../Transferrable/Transferrable.ipc.js')
    case ModuleId.WebView:
      return import('../WebView/WebView.ipc.ts')
    case ModuleId.SearchProcess:
      return import('../SearchProcess/SearchProcess.ipc.js')
    case ModuleId.ExtensionHostTextSearch:
      return import('../ExtensionHost/ExtensionHostTextSearch.ipc.js')
    case ModuleId.ExtensionStateStorage:
      return import('../ExtensionStateStorage/ExtensionStateStorage.js')
    case ModuleId.GetWindowId:
      return import('../GetWindowId/GetWindowId.ipc.js')
    case ModuleId.ElectronDialog:
      return import('../ElectronDialog/ElectronDialog.ipc.js')
    case ModuleId.Process:
      return import('../Process/Process.ipc.js')
    case ModuleId.ExtensionManagement:
      return import('../ExtensionManagement/ExtensionManagement.ipc.js')
    case ModuleId.Markdown:
      return import('../Markdown/Markdown.ipc.js')
    case ModuleId.MeasureTextHeight:
      return import('../MeasureTextHeight/MeasureTextHeight.ipc.js')
    default:
      throw new Error(`module ${moduleId} not found`)
  }
}
