import * as ForwardViewletCommand from '../ForwardViewletCommand/ForwardViewletCommand.js'

export const compositionEnd = ForwardViewletCommand.forwardViewletCommand('compositionEnd')
export const compositionStart = ForwardViewletCommand.forwardViewletCommand('compositionStart')
export const compositionUpdate = ForwardViewletCommand.forwardViewletCommand('compositionUpdate')
export const cut = ForwardViewletCommand.forwardViewletCommand('cut')
export const handleBeforeInputFromContentEditable = ForwardViewletCommand.forwardViewletCommand('handleBeforeInputFromContentEditable')
export const handleBlur = ForwardViewletCommand.forwardViewletCommand('blur')
export const handleContextMenu = ForwardViewletCommand.forwardViewletCommand('handleContextMenu')
export const handleMouseDown = ForwardViewletCommand.forwardViewletCommand('handleMouseDown')
export const handlePointerCaptureLost = ForwardViewletCommand.forwardViewletCommand('handlePointerCaptureLost')
export const handleScrollBarHorizontalMove = ForwardViewletCommand.forwardViewletCommand('handleScrollBarHorizontalMove')
export const handleScrollBarHorizontalPointerDown = ForwardViewletCommand.forwardViewletCommand('handleScrollBarHorizontalPointerDown')
export const handleScrollBarVerticalMove = ForwardViewletCommand.forwardViewletCommand('handleScrollBarMove')
export const handleScrollBarVerticalPointerDown = ForwardViewletCommand.forwardViewletCommand('handleScrollBarVerticalPointerDown')
export const handleTouchEnd = ForwardViewletCommand.forwardViewletCommand('handleTouchEnd')
export const handleTouchMove = ForwardViewletCommand.forwardViewletCommand('handleTouchMove')
export const handleTouchStart = ForwardViewletCommand.forwardViewletCommand('handleTouchStart')
export const moveRectangleSelectionPx = ForwardViewletCommand.forwardViewletCommand('moveRectangleSelectionPx')
export const moveSelectionPx = ForwardViewletCommand.forwardViewletCommand('moveSelectionPx')
export const paste = ForwardViewletCommand.forwardViewletCommand('patse')
export const setDelta = ForwardViewletCommand.forwardViewletCommand('setDelta')
export const type = ForwardViewletCommand.forwardViewletCommand('type')
export const typeWithAutoClosing = ForwardViewletCommand.forwardViewletCommand('typeWithAutoclosing')
