export const Panel = 'Panel'
export const SideBar = 'SideBar'
export const SecondarySideBar = 'SecondarySideBar'
export const Preview = 'Preview'
export const ActivityBar = 'ActivityBar'
export const None = ''
