export const DomException = 'DOMException'
export const RangeError = 'RangeError'
export const ReferenceError = 'ReferenceError'
export const SyntaxError = 'SyntaxError'
export const TypeError = 'TypeError'
export const UriError = 'URIError'
