export const CacheControl = 'Cache-Control'
export const ContentSecurityPolicy = 'Content-Security-Policy'
export const CrossOriginEmbedderPolicy = 'Cross-Origin-Embedder-Policy'
export const CrossOriginOpenerPolicy = 'Cross-Origin-Opener-Policy'
export const Etag = 'Etag'
export const IfNotMatch = 'if-none-match'
