import { CommandNotFoundError } from '../CommandNotFoundError/CommandNotFoundError.ts'
import * as ModuleId from '../ModuleId/ModuleId.ts'

export const getModuleId = (commandId: any): any => {
  switch (commandId) {
    case 4820:
      return ModuleId.TextDocument
    case 'AttachDebugger.attachDebugger':
      return ModuleId.AttachDebugger
    case 'AutoUpdater.getAutoUpdateType':
    case 'AutoUpdater.getLatestVersion':
      return ModuleId.AutoUpdater
    case 'AutoUpdaterAppImage.downloadUpdate':
    case 'AutoUpdaterAppImage.installAndRestart':
      return ModuleId.AutoUpdaterAppImage
    case 'AutoUpdaterWindowsNsis.downloadUpdate':
    case 'AutoUpdaterWindowsNsis.installAndRestart':
      return ModuleId.AutoUpdaterWindowsNsis
    case 'BulkReplacement.applyBulkReplacement':
      return ModuleId.BulkReplacement
    case 'ChromeExtension.install':
    case 'ChromeExtension.uninstall':
      return ModuleId.ChromeExtension
    case 'ClipBoard.readFiles':
    case 'ClipBoard.writeFiles':
      return ModuleId.ClipBoard
    case 'ContentSecurityPolicy.set':
      return ModuleId.ContentSecurityPolicy
    case 'Crash.crashMainProcess':
    case 'Crash.crashSharedProcess':
      return ModuleId.Crash
    case 'DesktopCapturer.getSources':
      return ModuleId.DesktopCapturer
    case 'Developer.allocateMemory':
    case 'Developer.crashSharedProcess':
    case 'Developer.createHeapSnapshot':
    case 'Developer.createProfile':
    case 'Developer.sharedProcessMemoryUsage':
    case 'Developer.sharedProcessStartupPerformance':
    case 'Developer.showGpuInfo':
      return ModuleId.Developer
    case 'Download.download':
      return ModuleId.Download
    case 'ElectronApplicationMenu.handleClick':
    case 'ElectronApplicationMenu.setItems':
      return ModuleId.ElectronApplicationMenu
    case 'ElectronClipBoard.writeText':
      return ModuleId.ElectronClipBoard
    case 'ElectronContentTracing.startRecording':
    case 'ElectronContentTracing.stopRecording':
      return ModuleId.ElectronContentTracing
    case 'ElectronContextMenu.openContextMenu':
      return ModuleId.ElectronContextMenu
    case 'ElectronDeveloper.getPerformanceEntries':
      return ModuleId.ElectronDeveloper
    case 'ElectronDialog.showMessageBox':
    case 'ElectronDialog.showOpenDialog':
    case 'ElectronDialog.showSaveDialog':
      return ModuleId.ElectronDialog
    case 'ElectronInitialize.electronInitialize':
      return ModuleId.ElectronInitialize
    case 'ElectronNet.getJson':
      return ModuleId.ElectronNet
    case 'ElectronNetLog.startLogging':
    case 'ElectronNetLog.stopLogging':
      return ModuleId.ElectronNetLog
    case 'ElectronPowerSaveBlocker.start':
    case 'ElectronPowerSaveBlocker.stop':
      return ModuleId.ElectronPowerSaveBlocker
    case 'ElectronProcess.getArgv':
    case 'ElectronProcess.getChromeVersion':
    case 'ElectronProcess.getElectronVersion':
    case 'ElectronProcess.writeStderr':
    case 'ElectronProcess.writeStdout':
      return ModuleId.ElectronProcess
    case 'ElectronWindow.close':
    case 'ElectronWindow.focus':
    case 'ElectronWindow.getZoom':
    case 'ElectronWindow.maximize':
    case 'ElectronWindow.minimize':
    case 'ElectronWindow.openNew':
    case 'ElectronWindow.openNewWithUri':
    case 'ElectronWindow.reload':
    case 'ElectronWindow.toggleDevtools':
    case 'ElectronWindow.toggleFullScreen':
    case 'ElectronWindow.unmaximize':
    case 'ElectronWindow.zoomIn':
    case 'ElectronWindow.zoomOut':
    case 'ElectronWindow.zoomReset':
      return ModuleId.Window
    case 'ElectronWindowAbout.open':
      return ModuleId.ElectronWindowAbout
    case 'ElectronWindowProcessExplorer.open':
      return ModuleId.ElectronWindowProcessExplorer
    case 'Exec.exec':
      return ModuleId.Exec
    case 'Exit.exit':
      return ModuleId.Exit
    case 'ExtensionHost.getColorThemeJson':
    case 'ExtensionHost.getColorThemeNames':
    case 'ExtensionHost.getColorThemes':
    case 'ExtensionHost.getIconTheme':
    case 'ExtensionHost.getIconThemeJson':
    case 'ExtensionHost.getLanguageConfiguration':
    case 'ExtensionHost.getLanguages':
    case 'ExtensionHost.getWebViews':
    case 'ExtensionHost.watchColorTheme':
    case 'ExtensionHost.watchForHotReload':
    case 'ExtensionManagement.disable':
    case 'ExtensionManagement.enable':
    case 'ExtensionManagement.getAllExtensions':
    case 'ExtensionManagement.getExtensions':
    case 'ExtensionManagement.getExtensionsEtag':
    case 'ExtensionManagement.getLinkedExtensionDevelopmentConfig':
    case 'ExtensionManagement.install':
    case 'ExtensionManagement.uninstall':
      return ModuleId.ExtensionManagement
    case 'FileSystem.chmod':
    case 'FileSystem.copy':
    case 'FileSystem.createFile':
    case 'FileSystem.createFolder':
    case 'FileSystem.ensureFile':
    case 'FileSystem.getPathSeparator':
    case 'FileSystem.getRealUri':
    case 'FileSystem.mkdir':
    case 'FileSystem.readDirWithFileTypes':
    case 'FileSystem.readFile':
    case 'FileSystem.readFileAsBuffer':
    case 'FileSystem.readJson':
    case 'FileSystem.remove':
    case 'FileSystem.rename':
    case 'FileSystem.writeFile':
      return ModuleId.FileSystem
    case 'FileSystemDisk.chmod':
    case 'FileSystemDisk.copy':
    case 'FileSystemDisk.getFolderSize':
    case 'FileSystemDisk.getPathSeparator':
    case 'FileSystemDisk.mkdir':
    case 'FileSystemDisk.readDirWithFileTypes':
    case 'FileSystemDisk.readFile':
    case 'FileSystemDisk.readJson':
    case 'FileSystemDisk.remove':
    case 'FileSystemDisk.rename':
    case 'FileSystemDisk.stat':
    case 'FileSystemDisk.writeFile':
      return ModuleId.FileSystemDisk
    case 'FileWatcher.handleChange':
    case 'FileWatcher.watch':
    case 'FileWatcher.watchFile2':
      return ModuleId.FileWatcher
    case 'FileWatcherExplorer.decreaseRefCount':
      return ModuleId.FileWatcherExplorer
    case 'FirefoxCookieImport.getInfo':
    case 'FirefoxCookieImport.importCookies':
      return ModuleId.FirefoxCookieImport
    case 'GetElectronFileResponse.getElectronFileResponse':
    case 'GetElectronFileResponse.resolveElectronFileUri':
      return ModuleId.GetElectronFileResponse
    case 'GetExtensions.getExtensions':
      return ModuleId.GetExtensions
    case 'GetTerminalSpawnOptions.getTerminalSpawnOptions':
      return ModuleId.GetTerminalSpawnOptions
    case 'GetWindowId.getWindowId':
      return ModuleId.GetWindowId
    case 'GitLsFiles.gitLsFiles':
    case 'GitLsFiles.gitLsFilesHash':
    case 'GitLsFiles.resolveGit':
      return ModuleId.GitLsFiles
    case 'HandleCliArgs.handleCliArgs':
      return ModuleId.HandleCliArgs
    case 'HandleElectronMessagePort.handleElectronMessagePort':
      return ModuleId.HandleElectronMessagePort
    case 'HandleElectronReady.handleElectronReady':
      return ModuleId.HandleElectronReady
    case 'HandleMessagePortForAuthProcess.handleAuthProcessIpcClosed':
    case 'HandleMessagePortForAuthProcess.handleMessagePortForAuthProcess':
      return ModuleId.HandleMessagePortForAuthProcess
    case 'HandleMessagePortForClipBoardProcess.handleMessagePortForClipBoardProcess':
      return ModuleId.HandleMessagePortForClipBoardProcess
    case 'HandleMessagePortForEmbedsProcess.handleEmbedsProcessIpcClosed':
    case 'HandleMessagePortForEmbedsProcess.handleMessagePortForEmbedsProcess':
      return ModuleId.HandleMessagePortForEmbedsProcess
    case 'HandleMessagePortForExtensionNodeProcess.handleMessagePortForExtensionNodeProcess':
      return ModuleId.HandleMessagePortForExtensionNodeProcess
    case 'HandleMessagePortForFileSystemProcess.handleMessagePortForFileSystemProcess':
      return ModuleId.HandleMessagePortForFileSystemProcess
    case 'HandleMessagePortForFileWatcherExplorer.handleMessagePortForFileWatcherExplorer':
      return ModuleId.HandleMessagePortForFileWatcherExplorer
    case 'HandleMessagePortForProcessExplorer.handleMessagePortForProcessExplorer':
      return ModuleId.HandleMessagePortForProcessExplorer
    case 'HandleMessagePortForSearchProcess.handleMessagePortForSearchProcess':
      return ModuleId.HandleMessagePortForSearchProcess
    case 'HandleMessagePortForTerminalProcess.handleMessagePortForTerminalProcess':
      return ModuleId.HandleMessagePortForTerminalProcess
    case 'HandleNodeMessagePort.handleNodeMessagePort':
      return ModuleId.HandleNodeMessagePort
    case 'HandleRequest.handleRequest':
      return ModuleId.HandleRequest
    case 'HandleWebSocket.handleWebSocket':
      return ModuleId.HandleWebSocket
    case 'HandleWindowAllClosed.handleWindowAllClosed':
      return ModuleId.HandleWindowAllClosed
    case 'InstallExtension.installExtension':
      return ModuleId.InstallExtension
    case 'IpcTrace.append':
      return ModuleId.IpcTrace
    case 'IsAutoUpdateSupported.isAutoUpdateSupported':
      return ModuleId.IsAutoUpdateSupported
    case 'LanguageServer.codeAction':
    case 'LanguageServer.complete':
    case 'LanguageServer.definition':
    case 'LanguageServer.diagnostic':
    case 'LanguageServer.dispose':
    case 'LanguageServer.disposeAll':
    case 'LanguageServer.documentSymbols':
    case 'LanguageServer.format':
    case 'LanguageServer.references':
      return ModuleId.LanguageServer
    case 'ListProcessesWithMemoryUsage.listProcessesWithMemoryUsage':
      return ModuleId.ListProcessesWithMemoryUsage
    case 'Native.openFolder':
    case 'OpenNativeFolder.openFolder':
      return ModuleId.OpenNativeFolder
    case 'OpenExternal.openExternal':
    case 'OpenExternal.showItemInFolder':
      return ModuleId.OpenExternal
    case 'Os.getTmpDir':
      return ModuleId.Os
    case 'OutputChannel.close':
    case 'OutputChannel.open':
      return ModuleId.OutputChannel
    case 'PassthroughElectronMessagePort.passThroughElectronMessagePort':
      return ModuleId.PassThroughElectronMessagePort
    case 'Performance.getNodeStartupTiming':
      return ModuleId.Performance
    case 'Platform.getAppDir':
    case 'Platform.getApplicationName':
    case 'Platform.getArch':
    case 'Platform.getBuiltinExtensionsPath':
    case 'Platform.getCachedExtensionsPath':
    case 'Platform.getCacheDir':
    case 'Platform.getCacheUri':
    case 'Platform.getCommit':
    case 'Platform.getConfigDir':
    case 'Platform.getConfigJsonPath':
    case 'Platform.getConfigUri':
    case 'Platform.getDataDir':
    case 'Platform.getDate':
    case 'Platform.getDisabledExtensionsPath':
    case 'Platform.getDownloadDir':
    case 'Platform.getExtensionsPath':
    case 'Platform.getHomeDir':
    case 'Platform.getLogsDir':
    case 'Platform.getMarketplaceUrl':
    case 'Platform.getProductNameLong':
    case 'Platform.getRecentlyOpenedPath':
    case 'Platform.getRoot':
    case 'Platform.getRootUri':
    case 'Platform.getTestPath':
    case 'Platform.getUserKeyBindingsPath':
    case 'Platform.getUserSettingsPath':
    case 'Platform.getVersion':
    case 'Platform.setEnvironmentVariables':
      return ModuleId.Platform
    case 'PlatformPaths.getDisabledExtensionsJsonPath':
    case 'PlatformPaths.getDisabledExtensionsJsonUri':
      return ModuleId.PlatformPaths
    case 'Preferences.getAll':
      return ModuleId.Preferences
    case 'Process.getArch':
    case 'Process.getArgv':
    case 'Process.getNodeVersion':
    case 'Process.getPid':
    case 'Process.getV8Version':
    case 'Process.kill':
      return ModuleId.Process
    case 'ProcessExplorer.decreaseRefCount':
      return ModuleId.ProcessExplorer
    case 'ProcessId.getMainProcessId':
    case 'ProcessId.getSharedProcessId':
      return ModuleId.ProcessId
    case 'RebuildNodePty.rebuildNodePty':
      return ModuleId.RebuildNodePty
    case 'RecentlyOpened.addPath':
      return ModuleId.RecentlyOpened
    case 'RemoteCli.open':
    case 'RemoteCli.waitForOpenRequest':
      return ModuleId.RemoteCli
    case 'Screen.getBounds':
    case 'Screen.getHeight':
    case 'Screen.getWidth':
      return ModuleId.Screen
    case 'SendMessagePortToMainProcess.sendMessagePortToMainProcess':
      return ModuleId.SendMessagePortToMainProcess
    case 'TemporaryMessagePort.getPortTuple2':
    case 'TemporaryMessagePort.getPortTuple3':
    case 'TemporaryMessagePort.handlePorts':
    case 'TemporaryMessagePort.sendTo2':
    case 'TemporaryMessagePort.sendToElectron':
      return ModuleId.TemporaryMessagePort
    case 'Terminal.create':
    case 'Terminal.dispose':
    case 'Terminal.resize':
    case 'Terminal.write':
      return ModuleId.Terminal
    case 'Transferrable.transfer':
      return ModuleId.Transferrable
    case 'WebViewServer.create':
    case 'WebViewServer.registerProtocol':
    case 'WebViewServer.setHandler':
    case 'WebViewServer.setInfo':
    case 'WebViewServer.setInfo2':
    case 'WebViewServer.start':
      return ModuleId.WebViewServer
    case 'Workspace.getHomeDir':
    case 'Workspace.resolveRoot':
      return ModuleId.Workspace
    default:
      throw new CommandNotFoundError(commandId)
  }
}
