import * as ModuleId from '../ModuleId/ModuleId.js'

export const getModuleId = (commandId) => {
  switch (commandId) {
    case 'ChromeExtension.install':
    case 'ChromeExtension.uninstall':
      return ModuleId.ChromeExtension
    case 'ClipBoard.readFiles':
    case 'ClipBoard.writeFiles':
      return ModuleId.ClipBoard
    case 'Developer.allocateMemory':
    case 'Developer.crashSharedProcess':
    case 'Developer.createHeapSnapshot':
    case 'Developer.createProfile':
    case 'Developer.getNodeStartupTime':
    case 'Developer.getNodeStartupTiming':
    case 'Developer.sharedProcessMemoryUsage':
    case 'Developer.sharedProcessStartupPerformance':
      return ModuleId.Developer
    case 'EXtensionHostRename.executePrepareRename':
    case 'ExtensionHost.dispose':
    case 'ExtensionHost.enableExtension':
    case 'ExtensionHost.executeCommand':
    case 'ExtensionHost.executeTabCompletionProvider':
    case 'ExtensionHost.format':
    case 'ExtensionHost.getMemoryUsage':
    case 'ExtensionHost.getSourceControlBadgeCount':
    case 'ExtensionHost.getStatusBarItems':
    case 'ExtensionHost.registerChangeListener':
    case 'ExtensionHost.setWorkspacePath':
    case 'ExtensionHost.sourceControlGetChangedFiles':
    case 'ExtensionHost.start':
    case 'ExtensionHostBraceCompletion.executeBraceCompletionProvider':
    case 'ExtensionHostClosingTag.execute':
    case 'ExtensionHostClosingTag.executeClosingTagProvider':
    case 'ExtensionHostClosingTag.executeTypeDefinitionProvider':
    case 'ExtensionHostCompletion.execute':
    case 'ExtensionHostDefinition.executeDefinitionProvider':
    case 'ExtensionHostDiagnostic.execute':
    case 'ExtensionHostFileSystem.getPathSeparator':
    case 'ExtensionHostFileSystem.readDirWithFileTypes':
    case 'ExtensionHostFileSystem.readFile':
    case 'ExtensionHostFileSystem.remove':
    case 'ExtensionHostFileSystem.rename':
    case 'ExtensionHostFileSystem.writeFile':
    case 'ExtensionHostHover.execute':
    case 'ExtensionHostImplementation.executeImplementationProvider':
    case 'ExtensionHostKeyBindings.getKeyBindings':
    case 'ExtensionHostLanguages.getLanguages':
    case 'ExtensionHostManagement.activateAll':
    case 'ExtensionHostManagement.enableExtensions':
    case 'ExtensionHostOutput.getOutputChannels':
    case 'ExtensionHostQuickPick.handleQuickPickResult':
    case 'ExtensionHostReferences.executeReferenceProvider':
    case 'ExtensionHostRename.executeRename':
    case 'ExtensionHostSemanticTokens.executeSemanticTokenProvider':
    case 'ExtensionHostSourceControl.acceptInput':
    case 'ExtensionHostTextDocument':
    case 'ExtensionHostTextDocument.setLanguageId':
    case 'ExtensionHostTextDocument.syncFull':
    case 'ExtensionHostTextDocument.syncIncremental':
    case 'ExtensionHostTextDocument.syncInitial':
    case 'ExtensionHostWorkspace.setWorkspacePath':
      return ModuleId.ExtensionHost
    case 'ExtensionHost.getColorThemeJson':
    case 'ExtensionHost.getColorThemeNames':
    case 'ExtensionHost.getColorThemes':
    case 'ExtensionHost.getIconTheme':
    case 'ExtensionHost.getIconThemeJson':
    case 'ExtensionHost.getLanguageConfiguration':
    case 'ExtensionHost.getLanguages':
    case 'ExtensionHost.watchColorTheme':
    case 'ExtensionManagement.disable':
    case 'ExtensionManagement.enable':
    case 'ExtensionManagement.getAllExtensions':
    case 'ExtensionManagement.getExtensions':
    case 'ExtensionManagement.install':
    case 'ExtensionManagement.uninstall':
      return ModuleId.ExtensionManagement
    case 'FileSystem.chmod':
    case 'FileSystem.copy':
    case 'FileSystem.createFile':
    case 'FileSystem.createFolder':
    case 'FileSystem.ensureFile':
    case 'FileSystem.getPathSeparator':
    case 'FileSystem.mkdir':
    case 'FileSystem.readDirWithFileTypes':
    case 'FileSystem.readFile':
    case 'FileSystem.remove':
    case 'FileSystem.rename':
    case 'FileSystem.writeFile':
      return ModuleId.FileSystem
    case 'Native.openFolder':
      return ModuleId.Native
    case 'OutputChannel.close':
    case 'OutputChannel.open':
      return ModuleId.OutputChannel
    case 'Platform.getAppDir':
    case 'Platform.getBuiltinExtensionsPath':
    case 'Platform.getCacheDir':
    case 'Platform.getCachedExtensionsPath':
    case 'Platform.getConfigDir':
    case 'Platform.getDataDir':
    case 'Platform.getDisabledExtensionsPath':
    case 'Platform.getExtensionsPath':
    case 'Platform.getHomeDir':
    case 'Platform.getLogsDir':
    case 'Platform.getMarketplaceUrl':
    case 'Platform.getRecentlyOpenedPath':
    case 'Platform.getTestPath':
    case 'Platform.getUserSettingsPath':
    case 'Platform.setEnvironmentVariables':
      return ModuleId.Platform
    case 'Preferences.getAll':
      return ModuleId.Preferences
    case 'RecentlyOpened.addPath':
      return ModuleId.RecentlyOpened
    case 'Search.search':
      return ModuleId.Search
    case 'SearchFile.searchFile':
      return ModuleId.SearchFile
    case 'Terminal.create':
    case 'Terminal.dispose':
    case 'Terminal.resize':
    case 'Terminal.write':
      return ModuleId.Terminal
    case 4820:
      return ModuleId.TextDocument
    case 5621:
      return ModuleId.WebSocketServer
    case 'Workspace.getHomeDir':
    case 'Workspace.resolveRoot':
      return ModuleId.Workspace
    default:
      throw new Error(`command ${commandId} not found`)
  }
}
