export const Css = [
  '/css/parts/Button.css',
  '/css/parts/Chevron.css',
  '/css/parts/Drag.css',
  '/css/parts/ExplorerInputBox.css',
  '/css/parts/FileIcon.css',
  '/css/parts/InputBox.css',
  '/css/parts/Label.css',
  '/css/parts/MaskIcon.css',
  '/css/parts/ScrollBar.css',
  '/css/parts/ScrollBarThumb.css',
  '/css/parts/TreeItem.css',
  '/css/parts/ViewletExplorer.css',
  '/css/parts/ViewletList.css',
  '/css/parts/Welcome.css',
]
