exports.WillLoadUrl = 'code/willLoadUrl'
exports.DidLoadUrl = 'code/didLoadUrl'
exports.AppReady = 'code/appReady'
exports.WillStartSharedProcess = 'code/willStartSharedProcess'
exports.DidStartSharedProcess = 'code/didStartSharedProcess'
