exports.Font = 'font'
exports.Image = 'image'
exports.MainFrame = 'mainFrame'
exports.Media = 'media'
exports.Script = 'script'
exports.Stylesheet = 'stylesheet'
exports.SubFrame = 'subFrame'
exports.Xhr = 'xhr'
