exports.ENOENT = 'ENOENT'

exports.EXDEV = 'EXDEV'

exports.EEXIST = 'EEXIST'

exports.ENOTDIR = 'ENOTDIR'

exports.E_MANIFEST_NOT_FOUND = 'E_MANIFEST_NOT_FOUND'

exports.ESRCH = 'ESRCH'

exports.EIO = 'EIO'

exports.MODULE_NOT_FOUND = 'MODULE_NOT_FOUND'

exports.E_COMMAND_NOT_FOUND = 'E_COMMAND_NOT_FOUND'

exports.E_MODULE_NOT_FOUND = 'E_MODULE_NOT_FOUND'

exports.ERR_DLOPEN_FAILED = 'ERR_DLOPEN_FAILED'
