import * as SimpleBrowser from './ViewletSimpleBrowser.js'
import * as ViewletSimpleBrowserGetDomTree from './ViewletSimpleBrowserGetDomTree.js'
import * as ViewletSimpleBrowserHandleContextMenu from './ViewletSimpleBrowserHandleContextMenu.js'
import * as ViewletSimpleBrowserInsertCss from './ViewletSimpleBrowserInsertCss.js'
import * as ViewletSimpleBrowserInsertJavaScript from './ViewletSimpleBrowserInsertJavaScript.js'

export const Commands = {
  acceptSuggestion: SimpleBrowser.acceptSuggestion,
  applySuggestions: SimpleBrowser.applySuggestions,
  closeSuggestions: SimpleBrowser.closeSuggestions,
  closeCurrentTab: SimpleBrowser.closeCurrentTab,
  closeOtherTabs: SimpleBrowser.closeOtherTabs,
  closeTab: SimpleBrowser.closeTab,
  closeTabsToTheLeft: SimpleBrowser.closeTabsToTheLeft,
  closeTabsToTheRight: SimpleBrowser.closeTabsToTheRight,
  createNewTab: SimpleBrowser.createNewTab,
  duplicateTab: SimpleBrowser.duplicateTab,
  focusNextTab: SimpleBrowser.focusNextTab,
  focusPreviousTab: SimpleBrowser.focusPreviousTab,
  getDomTree: ViewletSimpleBrowserGetDomTree.getDomTree,
  go: SimpleBrowser.go,
  handleAudioStateChanged: SimpleBrowser.handleAudioStateChanged,
  handleDidNavigate: SimpleBrowser.handleDidNavigate,
  handleDidNavigationCancel: SimpleBrowser.handleDidNavigationCancel,
  handleFocusIn: SimpleBrowser.handleFocusIn,
  handleInput: SimpleBrowser.handleInput,
  handleKeyBinding: SimpleBrowser.handleKeyBinding,
  handlePageFaviconUpdated: SimpleBrowser.handlePageFaviconUpdated,
  handleTitleUpdated: SimpleBrowser.handleTitleUpdated,
  handleWillNavigate: SimpleBrowser.handleWillNavigate,
  hideTabHover: SimpleBrowser.hideTabHover,
  hideOverlay: SimpleBrowser.hideOverlay,
  muteTab: SimpleBrowser.muteTab,
  reloadTab: SimpleBrowser.reloadTab,
  insertCss: ViewletSimpleBrowserInsertCss.insertCss,
  insertJavaScript: ViewletSimpleBrowserInsertJavaScript.insertJavaScript,
  setUrl: SimpleBrowser.setUrl,
  selectNextSuggestion: SimpleBrowser.selectNextSuggestion,
  selectPreviousSuggestion: SimpleBrowser.selectPreviousSuggestion,
  selectTab: SimpleBrowser.selectTab,
  showOverlay: SimpleBrowser.showOverlay,
  showTabHover: SimpleBrowser.showTabHover,
}

export const LazyCommands = {
  openExternal: () => import('./ViewletSimpleBrowserOpenExternal.js'),
  openHistory: () => import('./ViewletSimpleBrowserOpenHistory.js'),
  openDownloads: () => import('./ViewletSimpleBrowserOpenDownloads.js'),
  openBackgroundTab: () => import('./ViewletSimpleBrowserOpenBackgroundTab.js'),
  handleContextMenu: () => import('./ViewletSimpleBrowserHandleContextMenu.js'),
  handleTabContextMenu: () => import('./ViewletSimpleBrowserHandleTabContextMenu.js'),
  inspectElement: () => import('./ViewletSimpleBrowserInspectElement.js'),
  copyImage: () => import('./ViewletSimpleBrowserCopyImage.js'),
  backward: () => import('./ViewletSimpleBrowserBackward.js'),
  forward: () => import('./ViewletSimpleBrowserForward.js'),
  importFirefoxCookies: () => import('./ViewletSimpleBrowserImportFirefoxCookies.js'),
  openDevtools: () => import('./ViewletSimpleBrowserOpenDevtools.js'),
  reload: () => import('./ViewletSimpleBrowserReload.js'),
  showMenu: () => import('./ViewletSimpleBrowserShowMenu.js'),
  toggleDevTools: () => import('./ViewletSimpleBrowserToggleDevTools.js'),
  resetZoom: () => import('./ViewletSimpleBrowserZoom.js'),
  zoomIn: () => import('./ViewletSimpleBrowserZoom.js'),
  zoomOut: () => import('./ViewletSimpleBrowserZoom.js'),
  cancelNavigation: () => import('./ViewletSimpleBrowserCancelNavigation.js'),
}

export const Events = {
  'browser-view-audio-state-changed': SimpleBrowser.handleAudioStateChanged,
  'browser-view-context-menu': ViewletSimpleBrowserHandleContextMenu.handleContextMenu,
  'browser-view-did-navigate': SimpleBrowser.handleDidNavigate,
  'browser-view-key-binding': SimpleBrowser.handleKeyBinding,
  'browser-view-page-favicon-updated': SimpleBrowser.handlePageFaviconUpdated,
  'browser-view-title-updated': SimpleBrowser.handleTitleUpdated,
  'browser-view-will-navigate': SimpleBrowser.handleWillNavigate,
  'browser-view-window-open': SimpleBrowser.handleWindowOpen,
}
