export const Boolean = 'boolean'
export const None = ''
export const Number = 'number'
export const Object = 'object'
export const String = 'String'
export const Symbol = 'symbol'
export const Undefined = 'undefined'
