import * as ViewletTerminals from './ViewletTerminals.js'

export const Commands = {
  handleDrop: ViewletTerminals.handleDrop,
  attachTerminal: ViewletTerminals.attachTerminal,
  detachTerminal: ViewletTerminals.detachTerminal,
  handleTabPointerDown: ViewletTerminals.handleTabPointerDown,
  handleDragStart: ViewletTerminals.handleDragStart,
  handleDragEnd: ViewletTerminals.handleDragEnd,
  handleDragOver: ViewletTerminals.handleDragOver,
  addTerminal: ViewletTerminals.addTerminal,
  handleClickAction: ViewletTerminals.handleClickAction,
  handleClickTab: ViewletTerminals.handleClickTab,
  handleClickTerminalTabAction: ViewletTerminals.handleClickTerminalTabAction,
  handleTabContextMenu: ViewletTerminals.handleTabContextMenu,
  startRenameTerminal: ViewletTerminals.startRenameTerminal,
  acceptRenameTerminal: ViewletTerminals.acceptRenameTerminal,
  cancelRenameTerminal: ViewletTerminals.cancelRenameTerminal,
  handleRenameTerminalFocus: ViewletTerminals.handleRenameTerminalFocus,
  handleRenameTerminalPointerDown: ViewletTerminals.handleRenameTerminalPointerDown,
  handleRenameTerminalKeyDown: ViewletTerminals.handleRenameTerminalKeyDown,
  handleMouseDown: ViewletTerminals.handleMouseDown,
  handleTerminalExit: ViewletTerminals.handleTerminalExit,
  killTerminal: ViewletTerminals.killTerminal,
  sendText: ViewletTerminals.sendText,
  splitTerminal: ViewletTerminals.splitTerminal,
}
