import * as LazyCommand from '../LazyCommand/LazyCommand.js'
import * as ViewletEditorText from './ViewletEditorText.js'

// prettier-ignore
const Imports = {
  ApplyEdit: () => import('../EditorCommand/EditorCommandApplyEdit.js'),
  Blur: () => import('../EditorCommand/EditorCommandBlur.js'),
  BraceCompletion: () => import('../EditorCommand/EditorCommandBraceCompletion.js'),
  CancelSelection: () => import('../EditorCommand/EditorCommandCancelSelection.js'),
  ContextMenu: () => import('../EditorCommand/EditorCommandHandleContextMenu.js'),
  CopyLineDown: () => import('../EditorCommand/EditorCommandCopyLineDown.js'),
  CopyLineUp: () => import('../EditorCommand/EditorCommandCopyLineUp.js'),
  CursorCharacterLeft: () => import('../EditorCommand/EditorCommandCursorCharacterLeft.js'),
  CursorCharacterRight: () => import('../EditorCommand/EditorCommandCursorCharacterRight.js'),
  CursorDown: () => import('../EditorCommand/EditorCommandCursorDown.js'),
  CursorEnd: () => import('../EditorCommand/EditorCommandCursorEnd.js'),
  CursorHome: () => import('../EditorCommand/EditorCommandCursorHome.js'),
  CursorSet: () => import('../EditorCommand/EditorCommandCursorSet.js'),
  CursorUp: () => import('../EditorCommand/EditorCommandCursorUp.js'),
  CursorWordLeft: () => import('../EditorCommand/EditorCommandCursorWordLeft.js'),
  CursorWordPartLeft: () => import('../EditorCommand/EditorCommandCursorWordPartLeft.js'),
  CursorWordPartRight: () => import('../EditorCommand/EditorCommandCursorWordPartRight.js'),
  CursorWordRight: () => import('../EditorCommand/EditorCommandCursorWordRight.js'),
  Cut: () => import('../EditorCommand/EditorCommandCut.js'),
  DeleteAllLeft: () => import('../EditorCommand/EditorCommandDeleteAllLeft.js'),
  DeleteAllRight: () => import('../EditorCommand/EditorCommandDeleteAllRight.js'),
  DeleteLeft: () => import('../EditorCommand/EditorCommandDeleteCharacterLeft.js'),
  DeleteRight: () => import('../EditorCommand/EditorCommandDeleteCharacterRight.js'),
  DeleteWordLeft: () => import('../EditorCommand/EditorCommandDeleteWordLeft.js'),
  DeleteWordPartLeft: () => import('../EditorCommand/EditorCommandDeleteWordPartLeft.js'),
  DeleteWordPartRight: () => import('../EditorCommand/EditorCommandDeleteWordPartRight.js'),
  DeleteWordRight: () => import('../EditorCommand/EditorCommandDeleteWordRight.js'),
  EditorCompletion: () => import('../EditorCommand/EditorCommandCompletion.js'),
  EditorComposition: () => import('../EditorCommand/EditorCommandComposition.js'),
  EditorCopy: () => import('../EditorCommand/EditorCommandCopy.js'),
  EditorFind: () => import('../EditorCommand/EditorCommandOpenFind.js'),
  EditorSetSelections: () => import('../EditorCommand/EditorCommandSetSelections.js'),
  Format: () => import('../EditorCommand/EditorCommandFormat.js'),
  GoToDefinition: () => import('../EditorCommand/EditorCommandGoToDefinition.js'),
  GoToTypeDefinition: () => import('../EditorCommand/EditorCommandGoToTypeDefinition.js'),
  HandleBeforeInputFromContentEditable: () => import('../EditorCommand/EditorCommandHandleNativeBeforeInputFromContentEditable.js'),
  HandleDoubleClick: () => import('../EditorCommand/EditorCommandHandleDoubleClick.js'),
  HandleMouseMove: () => import('../EditorCommand/EditorCommandHandleMouseMove.js'),
  HandleMouseMoveWithAltKey: () => import('../EditorCommand/EditorCommandHandleMouseMoveWithAltKey.js'),
  HandleNativeSelectionChange: () => import('../EditorCommand/EditorCommandHandleNativeSelectionChange.js'),
  HandleScrollBarClick: () => import('../EditorCommand/EditorCommandHandleScrollBarPointerDown.js'),
  HandleScrollBarMove: () => import('../EditorCommand/EditorCommandHandleScrollBarMove.js'),
  HandleSingleClick: () => import('../EditorCommand/EditorCommandHandleSingleClick.js'),
  HandleTab: () => import('../EditorCommand/EditorCommandHandleTab.js'),
  HandleTouchEnd: () => import('../EditorCommand/EditorCommandHandleTouchEnd.js'),
  HandleTouchMove: () => import('../EditorCommand/EditorCommandHandleTouchMove.js'),
  HandleTouchStart: () => import('../EditorCommand/EditorCommandHandleTouchStart.js'),
  HandleTripleClick: () => import('../EditorCommand/EditorCommandHandleTripleClick.js'),
  IndentLess: () => import('../EditorCommand/EditorCommandIndentLess.js'),
  IndentMore: () => import('../EditorCommand/EditorCommandIndentMore.js'),
  InsertLineBreak: () => import('../EditorCommand/EditorCommandInsertLineBreak.js'),
  MoveLineDown: () => import('../EditorCommand/EditorCommandMoveLineDown.js'),
  MoveLineUp: () => import('../EditorCommand/EditorCommandMoveLineUp.js'),
  MoveRectangleSelection: () => import('../EditorCommand/EditorCommandMoveRectangleSelection.js'),
  MoveRectangleSelectionPx: () => import('../EditorCommand/EditorCommandMoveRectangleSelectionPx.js'),
  MoveSelection: () => import('../EditorCommand/EditorCommandMoveSelection.js'),
  MoveSelectionPx: () => import('../EditorCommand/EditorCommandMoveSelectionPx.js'),
  Paste: () => import('../EditorCommand/EditorCommandPaste.js'),
  PasteText: () => import('../EditorCommand/EditorCommandPasteText.js'),
  Save: () => import('../EditorCommand/EditorCommandSave.js'),
  SelectAll: () => import('../EditorCommand/EditorCommandSelectAll.js'),
  SelectAllOccurrences: () => import('../EditorCommand/EditorCommandSelectAllOccurrences.js'),
  SelectCharacterLeft: () => import('../EditorCommand/EditorCommandSelectCharacterLeft.js'),
  SelectCharacterRight: () => import('../EditorCommand/EditorCommandSelectCharacterRight.js'),
  SelectDown: () => import('../EditorCommand/EditorCommandSelectDown.js'),
  SelectInsideString: () => import('../EditorCommand/EditorCommandSelectInsideString.js'),
  SelectLine: () => import('../EditorCommand/EditorCommandSelectLine.js'),
  SelectNextOccurrence: () => import('../EditorCommand/EditorCommandSelectNextOccurrence.js'),
  SelectUp: () => import('../EditorCommand/EditorCommandSelectUp.js'),
  SelectWord: () => import('../EditorCommand/EditorCommandSelectWord.js'),
  SelectWordLeft: () => import('../EditorCommand/EditorCommandSelectWordLeft.js'),
  SelectWordRight: () => import('../EditorCommand/EditorCommandSelectWordRight.js'),
  SetDecorations: () => import('../EditorCommand/EditorCommandSetDecorations.js'),
  SetDeltaY: () => import('../EditorCommand/EditorCommandSetDeltaY.js'),
  SetLanguageId: () => import('../EditorCommand/EditorCommandSetLanguageId.js'),
  SortLinesAscending: () => import('../EditorCommand/EditorCommandSortLinesAscending.js'),
  TabCompletion: () => import('../EditorCommand/EditorCommandTabCompletion.js'),
  ToggleBlockComment: () => import('../EditorCommand/EditorCommandToggleBlockComment.js'),
  ToggleComment: () => import('../EditorCommand/EditorCommandToggleComment.js'),
  Type: () => import('../EditorCommand/EditorCommandType.js'),
  Undo: () => import('../EditorCommand/EditorCommandUndo.js'),
  UnIndent: () => import('../EditorCommand/EditorCommandUnindent.js'),
}

// prettier-ignore
export const Commands = {
    // TODO command to set cursor position
  'Editor.applyEdit': LazyCommand.create('EditorText', Imports.ApplyEdit, 'editorApplyEdit'),
  'Editor.blur': LazyCommand.create('EditorText', Imports.Blur, 'editorBlur'), // TODO needed?
  'Editor.braceCompletion': LazyCommand.create('EditorText', Imports.BraceCompletion, 'editorBraceCompletion'),
  'Editor.cancelSelection': LazyCommand.create('EditorText', Imports.CancelSelection, 'editorCancelSelection'),
  'Editor.close': LazyCommand.create('EditorText', Imports.EditorCompletion, 'close'),
  'Editor.compositionEnd': LazyCommand.create('EditorText', Imports.EditorComposition,'editorCompositionEnd'),
  'Editor.compositionStart': LazyCommand.create('EditorText', Imports.EditorComposition,'editorCompositionStart'),
  'Editor.compositionUpdate': LazyCommand.create('EditorText', Imports.EditorComposition,'editorCompositionUpdate'),
  'Editor.copy': LazyCommand.create('EditorText', Imports.EditorCopy, 'editorCopy'),
  'Editor.copyLineDown': LazyCommand.create('EditorText', Imports.CopyLineDown, 'editorCopyLineDown'),
  'Editor.copyLineUp': LazyCommand.create('EditorText', Imports.CopyLineUp, 'editorCopyLineUp'),
  'Editor.cursorCharacterLeft': LazyCommand.create('EditorText', Imports.CursorCharacterLeft, 'editorCursorCharacterLeft'),
  'Editor.cursorCharacterRight': LazyCommand.create('EditorText', Imports.CursorCharacterRight, 'editorCursorCharacterRight'),
  'Editor.cursorDown': LazyCommand.create('EditorText', Imports.CursorDown, 'editorCursorDown'),
  'Editor.cursorEnd': LazyCommand.create('EditorText', Imports.CursorEnd, 'editorCursorEnd'),
  'Editor.cursorHome': LazyCommand.create('EditorText', Imports.CursorHome, 'editorCursorsHome'),
  'Editor.cursorLeft': LazyCommand.create('EditorText', Imports.CursorCharacterLeft, 'editorCursorCharacterLeft'),
  'Editor.cursorRight': LazyCommand.create('EditorText', Imports.CursorCharacterRight, 'editorCursorCharacterRight'),
  'Editor.cursorSet': LazyCommand.create('EditorText', Imports.CursorSet, 'editorCursorSet') ,
  'Editor.cursorUp': LazyCommand.create('EditorText', Imports.CursorUp, 'editorCursorsUp'),
  'Editor.cursorWordLeft': LazyCommand.create('EditorText', Imports.CursorWordLeft, 'editorCursorWordLeft'),
  'Editor.cursorWordPartLeft': LazyCommand.create('EditorText', Imports.CursorWordPartLeft,'editorCursorWordPartLeft'),
  'Editor.cursorWordPartRight': LazyCommand.create('EditorText', Imports.CursorWordPartRight, 'editorCursorWordPartRight'),
  'Editor.cursorWordRight': LazyCommand.create('EditorText', Imports.CursorWordRight, 'editorCursorWordRight'),
  'Editor.cut': LazyCommand.create('EditorText', Imports.Cut, 'editorCut'),
  'Editor.deleteAllLeft': LazyCommand.create('EditorText', Imports.DeleteAllLeft, 'editorDeleteAllLeft'),
  'Editor.deleteAllRight': LazyCommand.create('EditorText', Imports.DeleteAllRight, 'editorDeleteAllRight'),
  'Editor.deleteLeft': LazyCommand.create('EditorText', Imports.DeleteLeft, 'editorDeleteCharacterLeft'),
  'Editor.deleteRight': LazyCommand.create('EditorText', Imports.DeleteRight, 'editorDeleteCharacterRight'),
  'Editor.deleteWordLeft': LazyCommand.create('EditorText', Imports.DeleteWordLeft, 'editorDeleteWordLeft'),
  'Editor.deleteWordPartLeft': LazyCommand.create('EditorText', Imports.DeleteWordPartLeft, 'editorDeleteWordPartLeft'),
  'Editor.deleteWordPartRight': LazyCommand.create('EditorText', Imports.DeleteWordPartRight, 'editorDeleteWordPartRight'),
  'Editor.deleteWordRight': LazyCommand.create('EditorText', Imports.DeleteWordRight, 'editorDeleteWordRight'),
  'Editor.format': LazyCommand.create('EditorText', Imports.Format, 'editorFormat'),
  'Editor.goToDefinition': LazyCommand.create('EditorText', Imports.GoToDefinition, 'editorGoToDefinition'),
  'Editor.goToTypeDefinition': LazyCommand.create('EditorText', Imports.GoToTypeDefinition, 'editorGoToTypeDefinition'),
  'Editor.handleBeforeInputFromContentEditable': LazyCommand.create('EditorText', Imports.HandleBeforeInputFromContentEditable, 'handleBeforeInputFromContentEditable'),
  'Editor.handleContextMenu': LazyCommand.create('EditorText', Imports.ContextMenu, 'editorHandleContextMenu'),
  'Editor.handleDoubleClick': LazyCommand.create('EditorText', Imports.HandleDoubleClick, 'editorHandleDoubleClick'),
  'Editor.handleMouseMove': LazyCommand.create('EditorText', Imports.HandleMouseMove, 'editorHandleMouseMove'),
  'Editor.handleMouseMoveWithAltKey': LazyCommand.create('EditorText', Imports.HandleMouseMoveWithAltKey, 'editorHandleMouseMoveWithAltKey'),
  'Editor.handleNativeSelectionChange': LazyCommand.create('EditorText', Imports.HandleNativeSelectionChange, 'editorHandleNativeSelectionChange'),
  'Editor.handleScrollBarMove': LazyCommand.create('EditorText', Imports.HandleScrollBarMove, 'editorHandleScrollBarMove'),
  'Editor.handleScrollBarPointerDown': LazyCommand.create('EditorText', Imports.HandleScrollBarClick, 'handleScrollBarPointerDown'),
  'Editor.handleSingleClick': LazyCommand.create('EditorText', Imports.HandleSingleClick, 'editorHandleSingleClick'),
  'Editor.handleTab': LazyCommand.create('EditorText', Imports.HandleTab, 'editorHandleTab'),
  'Editor.handleTouchEnd': LazyCommand.create('EditorText', Imports.HandleTouchEnd, 'editorHandleTouchEnd'),
  'Editor.handleTouchMove': LazyCommand.create('EditorText', Imports.HandleTouchMove, 'editorHandleTouchMove'),
  'Editor.handleTouchStart': LazyCommand.create('EditorText', Imports.HandleTouchStart, 'editorHandleTouchstart'),
  'Editor.handleTripleClick': LazyCommand.create('EditorText', Imports.HandleTripleClick, 'editorHandleTripleClick'),
  'Editor.indentLess': LazyCommand.create('EditorText', Imports.IndentLess, 'editorIndentLess'),
  'Editor.indentMore': LazyCommand.create('EditorText', Imports.IndentMore, 'editorIndentMore'),
  'Editor.insertLineBreak': LazyCommand.create('EditorText', Imports.InsertLineBreak, 'editorInsertLineBreak'),
  'Editor.moveLineDown': LazyCommand.create('EditorText', Imports.MoveLineDown, 'editorMoveLineDown'),
  'Editor.moveLineUp': LazyCommand.create('EditorText', Imports.MoveLineUp, 'editorMoveLineUp'),
  'Editor.moveRectangleSelection': LazyCommand.create('EditorText', Imports.MoveRectangleSelection, 'editorMoveRectangleSelection'),
  'Editor.moveRectangleSelectionPx': LazyCommand.create('EditorText', Imports.MoveRectangleSelectionPx, 'editorMoveRectangleSelectionPx'),
  'Editor.moveSelection': LazyCommand.create('EditorText', Imports.MoveSelection, 'editorMoveSelection'),
  'Editor.moveSelectionPx': LazyCommand.create('EditorText', Imports.MoveSelectionPx, 'editorMoveSelectionPx'),
  'Editor.openCompletion': LazyCommand.create('EditorText', Imports.EditorCompletion, 'open'),
  'Editor.openCompletionFromType': LazyCommand.create('EditorText', Imports.EditorCompletion, 'openFromType'),
  'Editor.openFind': LazyCommand.create('EditorText', Imports.EditorFind, 'openFind'),
  'Editor.paste': LazyCommand.create('EditorText', Imports.Paste, 'editorPaste'),
  'Editor.pasteText': LazyCommand.create('EditorText', Imports.PasteText, 'editorPasteText'),
  'Editor.save': LazyCommand.create('EditorText', Imports.Save, 'editorSave'),
  'Editor.selectAll': LazyCommand.create('EditorText', Imports.SelectAll, 'editorSelectAll'),
  'Editor.selectAllOccurrences': LazyCommand.create('EditorText', Imports.SelectAllOccurrences, 'editorSelectAllOccurrences'),
  'Editor.selectCharacterLeft': LazyCommand.create('EditorText', Imports.SelectCharacterLeft, 'editorSelectCharacterLeft'),
  'Editor.selectCharacterRight': LazyCommand.create('EditorText', Imports.SelectCharacterRight, 'editorSelectCharacterRight'),
  'Editor.selectDown': LazyCommand.create('EditorText', Imports.SelectDown, 'selectDown'),
  'Editor.selectInsideString': LazyCommand.create('EditorText', Imports.SelectInsideString, 'editorSelectInsideString'),
  'Editor.selectLine': LazyCommand.create('EditorText', Imports.SelectLine, 'editorSelectLine'),
  'Editor.selectNextOccurrence': LazyCommand.create('EditorText', Imports.SelectNextOccurrence, 'editorSelectNextOccurrence'),
  'Editor.selectUp': LazyCommand.create('EditorText', Imports.SelectUp, 'selectUp'),
  'Editor.selectWord': LazyCommand.create('EditorText', Imports.SelectWord, 'editorSelectWord'),
  'Editor.selectWordLeft': LazyCommand.create('EditorText', Imports.SelectWordLeft, 'editorSelectWordLeft'),
  'Editor.selectWordRight': LazyCommand.create('EditorText', Imports.SelectWordRight, 'editorSelectWordRight'),
  'Editor.setDecorations': LazyCommand.create('EditorText', Imports.SetDecorations, 'setDecorations'),
  'Editor.setDeltaY': LazyCommand.create('EditorText', Imports.SetDeltaY, 'editorSetDeltaY'),
  'Editor.setLanguageId': LazyCommand.create('EditorText', Imports.SetLanguageId, 'setLanguageId'),
  'Editor.setSelections': LazyCommand.create('EditorText', Imports.EditorSetSelections, 'setSelections'),
  'Editor.sortLinesAscending': LazyCommand.create('EditorText', Imports.SortLinesAscending, 'sortLinesAscending'),
  'Editor.tabCompletion': LazyCommand.create('EditorText', Imports.TabCompletion, 'editorTabCompletion'),
  'Editor.toggleBlockComment': LazyCommand.create('EditorText', Imports.ToggleBlockComment, 'editorToggleBlockComment'),
  'Editor.toggleComment': LazyCommand.create('EditorText', Imports.ToggleComment, 'editorToggleComment'),
  'Editor.type': LazyCommand.create('EditorText', Imports.Type, 'editorType'),
  'Editor.undo': LazyCommand.create('EditorText', Imports.Undo, 'editorUndo'),
  'Editor.unindent': LazyCommand.create('EditorText', Imports.UnIndent, 'selectUp'),
}

// prettier-ignore
export const Events = {
  'languages.changed': ViewletEditorText.handleLanguagesChanged,
  // 'editor.change': ViewletEditorText.handleEditorChange,
  // 'tokenizer.changed': ViewletEditorText.handleTokenizeChange,
}

export const Css = '/css/parts/Editor.css'

export * from './ViewletEditorText.js'
