import * as LazyCommand from '../LazyCommand/LazyCommand.js'
import * as ViewletEditorText from './ViewletEditorText.js'

// prettier-ignore
const Imports = {
  ApplyEdit: () => import('../EditorCommand/EditorCommandApplyEdit.js'),
  Blur: () => import('../EditorCommand/EditorCommandBlur.js'),
  BraceCompletion: () => import('../EditorCommand/EditorCommandBraceCompletion.js'),
  CancelSelection: () => import('../EditorCommand/EditorCommandCancelSelection.js'),
  ContextMenu: () => import('../EditorCommand/EditorCommandHandleContextMenu.js'),
  CopyLineDown: () => import('../EditorCommand/EditorCommandCopyLineDown.js'),
  CopyLineUp: () => import('../EditorCommand/EditorCommandCopyLineUp.js'),
  CursorCharacterLeft: () => import('../EditorCommand/EditorCommandCursorCharacterLeft.js'),
  CursorCharacterRight: () => import('../EditorCommand/EditorCommandCursorCharacterRight.js'),
  CursorDown: () => import('../EditorCommand/EditorCommandCursorDown.js'),
  CursorEnd: () => import('../EditorCommand/EditorCommandCursorEnd.js'),
  CursorHome: () => import('../EditorCommand/EditorCommandCursorHome.js'),
  CursorSet: () => import('../EditorCommand/EditorCommandCursorSet.js'),
  CursorUp: () => import('../EditorCommand/EditorCommandCursorUp.js'),
  CursorWordLeft: () => import('../EditorCommand/EditorCommandCursorWordLeft.js'),
  CursorWordPartLeft: () => import('../EditorCommand/EditorCommandCursorWordPartLeft.js'),
  CursorWordPartRight: () => import('../EditorCommand/EditorCommandCursorWordPartRight.js'),
  CursorWordRight: () => import('../EditorCommand/EditorCommandCursorWordRight.js'),
  Cut: () => import('../EditorCommand/EditorCommandCut.js'),
  DeleteAllLeft: () => import('../EditorCommand/EditorCommandDeleteAllLeft.js'),
  DeleteAllRight: () => import('../EditorCommand/EditorCommandDeleteAllRight.js'),
  DeleteLeft: () => import('../EditorCommand/EditorCommandDeleteCharacterLeft.js'),
  DeleteRight: () => import('../EditorCommand/EditorCommandDeleteCharacterRight.js'),
  DeleteWordLeft: () => import('../EditorCommand/EditorCommandDeleteWordLeft.js'),
  DeleteWordPartLeft: () => import('../EditorCommand/EditorCommandDeleteWordPartLeft.js'),
  DeleteWordPartRight: () => import('../EditorCommand/EditorCommandDeleteWordPartRight.js'),
  DeleteWordRight: () => import('../EditorCommand/EditorCommandDeleteWordRight.js'),
  EditorCompletion: () => import('../EditorCommand/EditorCommandCompletion.js'),
  EditorComposition: () => import('../EditorCommand/EditorCommandComposition.js'),
  EditorCopy: () => import('../EditorCommand/EditorCommandCopy.js'),
  EditorFind: () => import('../EditorCommand/EditorCommandOpenFind.js'),
  EditorSetSelections: () => import('../EditorCommand/EditorCommandSetSelections.js'),
  Format: () => import('../EditorCommand/EditorCommandFormat.js'),
  GoToDefinition: () => import('../EditorCommand/EditorCommandGoToDefinition.js'),
  GoToTypeDefinition: () => import('../EditorCommand/EditorCommandGoToTypeDefinition.js'),
  HandleBeforeInputFromContentEditable: () => import('../EditorCommand/EditorCommandHandleNativeBeforeInputFromContentEditable.js'),
  HandleDoubleClick: () => import('../EditorCommand/EditorCommandHandleDoubleClick.js'),
  HandleMouseMove: () => import('../EditorCommand/EditorCommandHandleMouseMove.js'),
  HandleMouseMoveWithAltKey: () => import('../EditorCommand/EditorCommandHandleMouseMoveWithAltKey.js'),
  HandleNativeSelectionChange: () => import('../EditorCommand/EditorCommandHandleNativeSelectionChange.js'),
  HandleScrollBarClick: () => import('../EditorCommand/EditorCommandHandleScrollBarPointerDown.js'),
  HandleScrollBarMove: () => import('../EditorCommand/EditorCommandHandleScrollBarMove.js'),
  HandleSingleClick: () => import('../EditorCommand/EditorCommandHandleSingleClick.js'),
  HandleTab: () => import('../EditorCommand/EditorCommandHandleTab.js'),
  HandleTouchEnd: () => import('../EditorCommand/EditorCommandHandleTouchEnd.js'),
  HandleTouchMove: () => import('../EditorCommand/EditorCommandHandleTouchMove.js'),
  HandleTouchStart: () => import('../EditorCommand/EditorCommandHandleTouchStart.js'),
  HandleTripleClick: () => import('../EditorCommand/EditorCommandHandleTripleClick.js'),
  IndentLess: () => import('../EditorCommand/EditorCommandIndentLess.js'),
  IndentMore: () => import('../EditorCommand/EditorCommandIndentMore.js'),
  InsertLineBreak: () => import('../EditorCommand/EditorCommandInsertLineBreak.js'),
  MoveLineDown: () => import('../EditorCommand/EditorCommandMoveLineDown.js'),
  MoveLineUp: () => import('../EditorCommand/EditorCommandMoveLineUp.js'),
  MoveRectangleSelection: () => import('../EditorCommand/EditorCommandMoveRectangleSelection.js'),
  MoveRectangleSelectionPx: () => import('../EditorCommand/EditorCommandMoveRectangleSelectionPx.js'),
  MoveSelection: () => import('../EditorCommand/EditorCommandMoveSelection.js'),
  MoveSelectionPx: () => import('../EditorCommand/EditorCommandMoveSelectionPx.js'),
  Paste: () => import('../EditorCommand/EditorCommandPaste.js'),
  PasteText: () => import('../EditorCommand/EditorCommandPasteText.js'),
  Save: () => import('../EditorCommand/EditorCommandSave.js'),
  SelectAll: () => import('../EditorCommand/EditorCommandSelectAll.js'),
  SelectAllOccurrences: () => import('../EditorCommand/EditorCommandSelectAllOccurrences.js'),
  SelectCharacterLeft: () => import('../EditorCommand/EditorCommandSelectCharacterLeft.js'),
  SelectCharacterRight: () => import('../EditorCommand/EditorCommandSelectCharacterRight.js'),
  SelectDown: () => import('../EditorCommand/EditorCommandSelectDown.js'),
  SelectInsideString: () => import('../EditorCommand/EditorCommandSelectInsideString.js'),
  SelectLine: () => import('../EditorCommand/EditorCommandSelectLine.js'),
  SelectNextOccurrence: () => import('../EditorCommand/EditorCommandSelectNextOccurrence.js'),
  SelectUp: () => import('../EditorCommand/EditorCommandSelectUp.js'),
  SelectWord: () => import('../EditorCommand/EditorCommandSelectWord.js'),
  SelectWordLeft: () => import('../EditorCommand/EditorCommandSelectWordLeft.js'),
  SelectWordRight: () => import('../EditorCommand/EditorCommandSelectWordRight.js'),
  SetDecorations: () => import('../EditorCommand/EditorCommandSetDecorations.js'),
  SetDeltaY: () => import('../EditorCommand/EditorCommandSetDeltaY.js'),
  SetLanguageId: () => import('../EditorCommand/EditorCommandSetLanguageId.js'),
  SortLinesAscending: () => import('../EditorCommand/EditorCommandSortLinesAscending.js'),
  TabCompletion: () => import('../EditorCommand/EditorCommandTabCompletion.js'),
  ToggleBlockComment: () => import('../EditorCommand/EditorCommandToggleBlockComment.js'),
  ToggleComment: () => import('../EditorCommand/EditorCommandToggleComment.js'),
  Type: () => import('../EditorCommand/EditorCommandType.js'),
  Undo: () => import('../EditorCommand/EditorCommandUndo.js'),
  UnIndent: () => import('../EditorCommand/EditorCommandUnindent.js'),
}

// prettier-ignore
export const Commands = {
    // TODO command to set cursor position
  applyEdit: LazyCommand.create('EditorText', Imports.ApplyEdit, 'applyEdit'),
  blur: LazyCommand.create('EditorText', Imports.Blur, 'blur'), // TODO needed?
  braceCompletion: LazyCommand.create('EditorText', Imports.BraceCompletion, 'braceCompletion'),
  cancelSelection: LazyCommand.create('EditorText', Imports.CancelSelection, 'cancelSelection'),
  close: LazyCommand.create('EditorText', Imports.EditorCompletion, 'close'),
  compositionEnd: LazyCommand.create('EditorText', Imports.EditorComposition,'compositionEnd'),
  compositionStart: LazyCommand.create('EditorText', Imports.EditorComposition,'compositionStart'),
  compositionUpdate: LazyCommand.create('EditorText', Imports.EditorComposition,'compositionUpdate'),
  copy: LazyCommand.create('EditorText', Imports.EditorCopy, 'copy'),
  copyLineDown: LazyCommand.create('EditorText', Imports.CopyLineDown, 'copyLineDown'),
  copyLineUp: LazyCommand.create('EditorText', Imports.CopyLineUp, 'copyLineUp'),
  cursorCharacterLeft: LazyCommand.create('EditorText', Imports.CursorCharacterLeft, 'cursorCharacterLeft'),
  cursorCharacterRight: LazyCommand.create('EditorText', Imports.CursorCharacterRight, 'cursorCharacterRight'),
  cursorDown: LazyCommand.create('EditorText', Imports.CursorDown, 'cursorDown'),
  cursorEnd: LazyCommand.create('EditorText', Imports.CursorEnd, 'cursorEnd'),
  cursorHome: LazyCommand.create('EditorText', Imports.CursorHome, 'cursorHome'),
  cursorLeft: LazyCommand.create('EditorText', Imports.CursorCharacterLeft, 'cursorCharacterLeft'),
  cursorRight: LazyCommand.create('EditorText', Imports.CursorCharacterRight, 'cursorCharacterRight'),
  cursorSet: LazyCommand.create('EditorText', Imports.CursorSet, 'cursorSet') ,
  cursorUp: LazyCommand.create('EditorText', Imports.CursorUp, 'cursorsUp'),
  cursorWordLeft: LazyCommand.create('EditorText', Imports.CursorWordLeft, 'cursorWordLeft'),
  cursorWordPartLeft: LazyCommand.create('EditorText', Imports.CursorWordPartLeft, 'cursorWordPartLeft'),
  cursorWordPartRight: LazyCommand.create('EditorText', Imports.CursorWordPartRight, 'cursorWordPartRight'),
  cursorWordRight: LazyCommand.create('EditorText', Imports.CursorWordRight, 'cursorWordRight'),
  cut: LazyCommand.create('EditorText', Imports.Cut, 'cut'),
  deleteAllLeft: LazyCommand.create('EditorText', Imports.DeleteAllLeft, 'deleteAllLeft'),
  deleteAllRight: LazyCommand.create('EditorText', Imports.DeleteAllRight, 'deleteAllRight'),
  deleteLeft: LazyCommand.create('EditorText', Imports.DeleteLeft, 'deleteCharacterLeft'),
  deleteRight: LazyCommand.create('EditorText', Imports.DeleteRight, 'deleteCharacterRight'),
  deleteWordLeft: LazyCommand.create('EditorText', Imports.DeleteWordLeft, 'deleteWordLeft'),
  deleteWordPartLeft: LazyCommand.create('EditorText', Imports.DeleteWordPartLeft, 'deleteWordPartLeft'),
  deleteWordPartRight: LazyCommand.create('EditorText', Imports.DeleteWordPartRight, 'deleteWordPartRight'),
  deleteWordRight: LazyCommand.create('EditorText', Imports.DeleteWordRight, 'deleteWordRight'),
  format: LazyCommand.create('EditorText', Imports.Format, 'format'),
  goToDefinition: LazyCommand.create('EditorText', Imports.GoToDefinition, 'goToDefinition'),
  goToTypeDefinition: LazyCommand.create('EditorText', Imports.GoToTypeDefinition, 'goToTypeDefinition'),
  handleBeforeInputFromContentEditable: LazyCommand.create('EditorText', Imports.HandleBeforeInputFromContentEditable, 'handleBeforeInputFromContentEditable'),
  handleContextMenu: LazyCommand.create('EditorText', Imports.ContextMenu, 'handleContextMenu'),
  handleDoubleClick: LazyCommand.create('EditorText', Imports.HandleDoubleClick, 'handleDoubleClick'),
  handleMouseMove: LazyCommand.create('EditorText', Imports.HandleMouseMove, 'handleMouseMove'),
  handleMouseMoveWithAltKey: LazyCommand.create('EditorText', Imports.HandleMouseMoveWithAltKey, 'handleMouseMoveWithAltKey'),
  handleNativeSelectionChange: LazyCommand.create('EditorText', Imports.HandleNativeSelectionChange, 'handleNativeSelectionChange'),
  handleScrollBarMove: LazyCommand.create('EditorText', Imports.HandleScrollBarMove, 'handleScrollBarMove'),
  handleScrollBarPointerDown: LazyCommand.create('EditorText', Imports.HandleScrollBarClick, 'handleScrollBarPointerDown'),
  handleSingleClick: LazyCommand.create('EditorText', Imports.HandleSingleClick, 'handleSingleClick'),
  handleTab: LazyCommand.create('EditorText', Imports.HandleTab, 'handleTab'),
  handleTouchEnd: LazyCommand.create('EditorText', Imports.HandleTouchEnd, 'handleTouchEnd'),
  handleTouchMove: LazyCommand.create('EditorText', Imports.HandleTouchMove, 'handleTouchMove'),
  handleTouchStart: LazyCommand.create('EditorText', Imports.HandleTouchStart, 'handleTouchstart'),
  handleTripleClick: LazyCommand.create('EditorText', Imports.HandleTripleClick, 'handleTripleClick'),
  indentLess: LazyCommand.create('EditorText', Imports.IndentLess, 'indentLess'),
  indentMore: LazyCommand.create('EditorText', Imports.IndentMore, 'indentMore'),
  insertLineBreak: LazyCommand.create('EditorText', Imports.InsertLineBreak, 'insertLineBreak'),
  moveLineDown: LazyCommand.create('EditorText', Imports.MoveLineDown, 'moveLineDown'),
  moveLineUp: LazyCommand.create('EditorText', Imports.MoveLineUp, 'moveLineUp'),
  moveRectangleSelection: LazyCommand.create('EditorText', Imports.MoveRectangleSelection, 'moveRectangleSelection'),
  moveRectangleSelectionPx: LazyCommand.create('EditorText', Imports.MoveRectangleSelectionPx, 'moveRectangleSelectionPx'),
  moveSelection: LazyCommand.create('EditorText', Imports.MoveSelection, 'moveSelection'),
  moveSelectionPx: LazyCommand.create('EditorText', Imports.MoveSelectionPx, 'moveSelectionPx'),
  openCompletion: LazyCommand.create('EditorText', Imports.EditorCompletion, 'open'),
  openCompletionFromType: LazyCommand.create('EditorText', Imports.EditorCompletion, 'openFromType'),
  openFind: LazyCommand.create('EditorText', Imports.EditorFind, 'openFind'),
  paste: LazyCommand.create('EditorText', Imports.Paste, 'paste'),
  pasteText: LazyCommand.create('EditorText', Imports.PasteText, 'pasteText'),
  save: LazyCommand.create('EditorText', Imports.Save, 'save'),
  selectAll: LazyCommand.create('EditorText', Imports.SelectAll, 'selectAll'),
  selectAllOccurrences: LazyCommand.create('EditorText', Imports.SelectAllOccurrences, 'selectAllOccurrences'),
  selectCharacterLeft: LazyCommand.create('EditorText', Imports.SelectCharacterLeft, 'selectCharacterLeft'),
  selectCharacterRight: LazyCommand.create('EditorText', Imports.SelectCharacterRight, 'selectCharacterRight'),
  selectDown: LazyCommand.create('EditorText', Imports.SelectDown, 'selectDown'),
  selectInsideString: LazyCommand.create('EditorText', Imports.SelectInsideString, 'selectInsideString'),
  selectLine: LazyCommand.create('EditorText', Imports.SelectLine, 'selectLine'),
  selectNextOccurrence: LazyCommand.create('EditorText', Imports.SelectNextOccurrence, 'selectNextOccurrence'),
  selectUp: LazyCommand.create('EditorText', Imports.SelectUp, 'selectUp'),
  selectWord: LazyCommand.create('EditorText', Imports.SelectWord, 'selectWord'),
  selectWordLeft: LazyCommand.create('EditorText', Imports.SelectWordLeft, 'selectWordLeft'),
  selectWordRight: LazyCommand.create('EditorText', Imports.SelectWordRight, 'selectWordRight'),
  setDecorations: LazyCommand.create('EditorText', Imports.SetDecorations, 'setDecorations'),
  setDeltaY: LazyCommand.create('EditorText', Imports.SetDeltaY, 'setDeltaY'),
  setLanguageId: LazyCommand.create('EditorText', Imports.SetLanguageId, 'setLanguageId'),
  setSelections: LazyCommand.create('EditorText', Imports.EditorSetSelections, 'setSelections'),
  sortLinesAscending: LazyCommand.create('EditorText', Imports.SortLinesAscending, 'sortLinesAscending'),
  tabCompletion: LazyCommand.create('EditorText', Imports.TabCompletion, 'tabCompletion'),
  toggleBlockComment: LazyCommand.create('EditorText', Imports.ToggleBlockComment, 'toggleBlockComment'),
  toggleComment: LazyCommand.create('EditorText', Imports.ToggleComment, 'toggleComment'),
  type: LazyCommand.create('EditorText', Imports.Type, 'type'),
  undo: LazyCommand.create('EditorText', Imports.Undo, 'undo'),
  unindent: LazyCommand.create('EditorText', Imports.UnIndent, 'selectUp'),
}

// prettier-ignore
export const Events = {
  'languages.changed': ViewletEditorText.handleLanguagesChanged,
  // 'editor.change': ViewletEditorText.handleEditorChange,
  // 'tokenizer.changed': ViewletEditorText.handleTokenizeChange,
}

export const Css = '/css/parts/ViewletEditor.css'

export * from './ViewletEditorText.js'
